src/ie/urls.py
from django.urls import include, path
from django.contrib import admin

" These two are to make file uploads work "
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('data/', include('staf.urls')),
    path('intranet/', include('team.urls')),
    path('', include('core.urls')),
    path('cities/', include('multiplicity.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/multiplicity/urls.py
from django.urls import path

from . import views

app_name = 'multiplicity'
urlpatterns = [

    # Admin

    path('admin/locations/', views.admin_locations, name='admin_locations'),
    path('admin/locations/<int:id>/', views.admin_location, name='admin_location'),
    path('admin/locations/create/', views.admin_location, name='admin_location_create'),

    path('admin/referencespaces/<slug:type>/', views.admin_referencespaces, name='admin_referencespaces'),
    path('admin/referencespaces/<slug:type>/<int:id>/', views.admin_referencespace, name='admin_referencespace'),
    path('admin/referencespaces/<slug:type>/<int:referencespace>/location/', views.admin_location, name='admin_referencespace_location'),
    path('admin/referencespaces/<slug:type>/create/', views.admin_referencespace, name='admin_referencespace_create'),

    path('admin/<slug:city>/overview/', views.admin_data_overview, name='admin_data_overview'),
    path('admin/overview/', views.admin_data_overview_all, name='admin_data_overview_all'),
    path('admin/<slug:city>/sector/<slug:sector>/activate/', views.admin_activate_sector, name='admin_activate_sector'),
    path('admin/<slug:city>/sector/<slug:sector>/deactivate/', views.admin_deactivate_sector, name='admin_deactivate_sector'),

    path('admin/datasettype/', views.admin_datasettypes, name='admin_datasettypes'),
    path('admin/datasettype/<int:id>/', views.admin_datasettype, name='admin_datasettype'),
    path('admin/datasettype/create/', views.admin_datasettype, name='admin_datasettype'),

    path('admin/referencephotos/', views.admin_referencephoto, name='admin_referencephotos'),
    path('admin/referencephotos/<int:id>/', views.admin_referencephoto, name='admin_referencephoto'),
    path('admin/referencephotos/create/', views.admin_referencephoto, name='admin_referencephoto'),
    path('admin/<slug:city>/mtu/<int:mtu>/delete/', views.admin_mtu_delete, name='admin_mtu_delete'),

    # General
    path('datasets/', views.datasets_all, name='datasets_all'),
    path('table/datasets/<int:dataset>/', views.datatable, name='datatable_dataset'),
    path('<slug:city>/checklist/', views.checklist, name='checklist'),

    path('', views.index, name='index'),
    path('<slug:city>/research/', views.research, name='research'),

    #path('<slug:city>/material-stocks/<slug:type>', views.flow, name='stock'),

    path('<slug:city>/material-flows/<slug:topic>/', views.datasets_overview, name='flows'),
    path('<slug:city>/material-stocks/<slug:topic>/', views.datasets_overview, {'type': 'stocks' }, name='stocks'),
    path('<slug:city>/energy-flows/<slug:topic>/', views.datasets_overview, {'type': 'energy'}, name='energy_flows'),

    #path('<slug:city>/material-flows/<slug:slug>', views.overview, name='overview_flows'),
    #path('<slug:city>/material-flows/<slug:slug>/<slug:type>', views.flow, name='flow'),
    #path('<slug:city>/material-stocks', views.overview, {'slug': 'material-stocks' }, name='overview_stocks'),

    path('<slug:city>/profile/<slug:topic>/', views.topic, name='topic'),
    #path('<slug:city>/<slug:topic>', views.topic, name='topic'),

    path('<slug:city>/maps/', views.map, name='map'),
    path('<slug:city>/maps/mtu/', views.mtu_map, name='map_mtu'),
    path('<slug:city>/maps/infrastructure/', views.map_infrastructure, name='map_infrastructure'),
    path('<slug:city>/maps/other/', views.photos, {'type': 'map'}, name='map_other'),
    path('<slug:city>/maps/<slug:type>/', views.map, name='map'),
    path('<slug:city>/mtu/<slug:type>/<slug:space>/', views.space, name='mtu_space'),
    path('<slug:city>/maps/mtu/<slug:type>/', views.mtu_map, name='map_mtu'),
    path('<slug:city>/maps/mtu/<slug:type>/download/', views.download_mtu, name='download_mtu'),
    path('<slug:city>/maps/boundaries/<int:id>/', views.map, name='map'),
    path('<slug:city>/maps/boundaries/<int:id>/download/', views.download_location, name='download_location'),
    path('<slug:city>/datasets/', views.datasets, name='datasets'),
    path('<slug:city>/resources/photos/', views.photos, name='photos'),
    path('<slug:city>/resources/videos/', views.videos, name='videos'),
    path('<slug:city>/resources/links/', views.topic, {'topic': 'links'}, name='links'),
    path('<slug:city>/resources/<slug:slug>/', views.resources, name='resources'),
    path('<slug:city>/datasets/<int:id>/', views.dataset, name='dataset'),
    path('<slug:city>/download/csv/<int:id>/', views.download_csv, name='download_csv'),
    path('<slug:city>/datasets/<int:id>/delete/', views.delete_dataset, name='delete_dataset'),
    path('<slug:city>/datasets/<int:id>/reset/', views.reset_dataset, name='reset_dataset'),
    path('<slug:city>/datasets/<int:dataset>/graph/<int:id>/', views.graph, name='graph'),
    path('<slug:city>/datasets/<int:dataset>/graph/<int:id>/space/<int:space>/', views.graph, name='graph'),
    path('<slug:city>/datasets/<int:id>/<slug:slug>/', views.dataset, name='dataset_slice'),
    path('<slug:city>/information/', views.information_form, name='information_form'),
    path('<slug:city>/information/topic/<int:topic>/', views.information_form, name='information_form_topic'),
    path('<slug:city>/information/<int:id>/', views.information_form, name='information_form'),
    path('<slug:city>/map/', views.photo_form, {'map': True}, name='map_form'),
    path('<slug:city>/sectors/<slug:sector>/', views.sector, name='sector'),

    # Downloading data
    path('<slug:city>/download/', views.download, name='download'),

    # Uploading data
    path('<slug:city>/upload/', views.upload, name='upload'),

    # Uploading infrastructure data
    path('<slug:city>/upload/infrastructure/', views.upload_infrastructure, name='upload_infrastructure'),
    path('<slug:city>/upload/infrastructure/<slug:type>/', views.upload_infrastructure_file, name='upload_infrastructure_file'),
    path('<slug:city>/upload/infrastructure/<slug:type>/sample/', views.upload_infrastructure_file_sample, name='upload_infrastructure_file_sample'),
    path('<slug:city>/upload/infrastructure/<slug:type>/<int:id>/', views.upload_infrastructure_review, name='upload_infrastructure_review'),
    path('<slug:city>/upload/infrastructure/<slug:type>/<int:id>/meta/', views.upload_infrastructure_meta, name='upload_infrastructure_meta'),

    # Uploading flows/stocks data
    path('<slug:city>/upload/flow/', views.upload_flow, name='upload_flow'),
    path('<slug:city>/upload/flow/<int:id>/', views.upload_flow_file, name='upload_flow_file'),
    path('<slug:city>/upload/flow/<int:id>/sample/', views.upload_flow_file_sample, name='upload_flow_file_sample'),
    path('<slug:city>/upload/flow/<int:type>/<int:id>/update/<int:update>/', views.upload_flow_review, name='upload_flow_review'),
    path('<slug:city>/upload/flow/<int:type>/<int:id>/', views.upload_flow_review, name='upload_flow_review'),
    path('<slug:city>/upload/flow/<int:type>/<int:id>/meta/', views.upload_flow_meta, name='upload_flow_meta'),
    path('<slug:city>/upload/stock/', views.upload_flow, {'type': 'stocks'}, name='upload_stock'),

    # Uploading reference
    path('<slug:city>/upload/resources/<int:type>/', views.reference_form, name='reference_form'),

    # Uploading geospatial data
    path('<slug:city>/upload/systemboundaries/', views.upload_systemboundaries, name='upload_systemboundaries'),
    path('<slug:city>/upload/systemboundaries/create/', views.upload_systemboundary, name='upload_systemboundary'),
    path('<slug:city>/upload/systemboundaries/<int:location>/', views.upload_systemboundary, name='upload_systemboundary'),

    path('<slug:city>/upload/mtu/', views.upload_mtu, name='upload_mtu'),
    path('<slug:city>/upload/mtu/<slug:filename>/', views.upload_mtu_review, name='upload_mtu_review'),

    # Uploading multimedia
    path('<slug:city>/photo/', views.photo_form, name='photo_form'),
    path('<slug:city>/photo/<int:id>/', views.photo_form, name='photo_form'),

    path('<slug:city>/upload/video/', views.upload_video, name='upload_video'),
    path('<slug:city>/upload/video/<int:id>/', views.upload_video, name='upload_video'),

    path('<slug:city>/infrastructure/<slug:type>/<slug:space>/', views.space, name='space'),
    path('<slug:city>/infrastructure/<slug:type>/', views.space_list, name='space_list'),
    path('<slug:city>/infrastructure/<slug:topic>/', views.infrastructure_list, name='infrastructure_list'),
    path('<slug:city>/infrastructure/', views.infrastructure_list, name='infrastructure_list'),

    path('<slug:city>/<slug:main>/<slug:topic>/', views.topic, name='subtopic'),
    path('<slug:city>/<slug:main>/<slug:topic>/input/', views.topic, {'tab': 'input'}, name='subtopic_input'),
    path('<slug:city>/<slug:main>/<slug:topic>/use/', views.topic, {'tab': 'use' }, name='subtopic_use'),
    path('<slug:city>/<slug:main>/<slug:topic>/output/', views.topic, {'tab': 'output'}, name='subtopic_output'),
    #path('<slug:city>/<slug:theme>/<slug:topic>/<slug:type>', views.space_list, name='space_list'),

    # This view is used to show the content of a slide, when recording a video
    path('<slug:city>/slide/', views.temp_slide, name='temp_slide'),

    path('materials/', views.materials, name='materials'),
    path('materials/<slug:catalog>/', views.materials, name='materials'),
    path('<slug:slug>/', views.index, name='city'),
    #path('profile', views.detail, name='profile'),

    # AJAX
    path('search/ajax', views.referencespace_search_ajax, name='referencespace_search_ajax'),

]

src/staf/urls.py
from django.urls import path

from . import views

app_name = 'staf'
urlpatterns = [
    path('', views.index, name='index'),
    path('search', views.search, name='search'),
    path('search/ajax', views.searchajax, name='searchajax'),

    path('processgroups', views.processgroups, name='processgroups'),
    path('processgroups/<int:id>', views.processgroup, name='processgroup'),

    path('materials', views.materiallist, name='materials'),
    path('materials/<int:id>', views.materiallist, name='materiallist'),
    path('materials/<int:id>/edit', views.materialform, name='material_edit'),
    path('materials/<int:id>/child', views.materialchild, name='material_child'),
    path('materials/create', views.materialform, name='material_create'),
    path('materials/ajax', views.materiallistajax, name='materialajax'),
    path('materials/ajax/select2', views.material_search_ajax, name='material_search_ajax'),

    path('processes', views.processlist, name='processes'),
    path('processes/table', views.processtable, name='processtable'),
    path('processes/<int:id>', views.processlist, name='processlist'),
    path('processes/<int:id>/edit', views.processform, name='process_edit'),
    path('processes/<int:id>/child', views.processchild, name='process_child'),
    path('processes/create', views.processform, name='process_create'),
    path('processes/ajax', views.processlistajax, name='processajax'),

    path('processbrowser', views.processlisting, name='processlisting'),
    path('processbrowser/tree', views.processtree, name='processbrowsertree'),
    path('processbrowser/<int:id>', views.processlisting, name='processlisting'),

    path('units', views.units, name='units'),
    path('units/<int:id>', views.unit, name='unit'),

]

src/templates/staf/datafile.review.html
{% extends 'multiplicity/base.html' %}
{% load bootstrap3 %}
{% load static %}

{% block title %}Flows | {{ info.name }}{% endblock %}
{% block container %}stretch-bg-head{% endblock %}

{% block content %}


<div class="panel">
  <div class="panel-heading">

  {% include 'staf/includes/dataset.topnav.html' %}

  </div>
  <div class="panel-body">

    <h4>Review data</h4>
    <p>File: <strong>{{ file.original_name }}</strong></p>

    <table class="table table-striped datatable">
      <thead>
        <tr>
          <th>Timeframe</th>
          <th>Material</th>
          <th>Quantity</th>
          {% if show_origin %}
              <th>Origin</th>
          {% endif %}
          {% if show_destination %}
              <th>Destination</th>
          {% endif %}
          {% if show_concentration %}
              <th>Concentration</th>
          {% endif %}
          {% if show_subset %}
              <th>Subset</th>
          {% endif %}
        </tr>
        </thead>
        <tbody>
          {% for details in data %}
            <tr>
              <td data-order="{{ details.from }}"><span class="date" title="From {{ details.from }} to {{ details.to }}">{{ details.timeframe }}</span></td>
              <td>{{ details.material }}</td>
              <td>{{ details.quantity }} {{ details.unit }}</td>
              {% if show_origin %}
                  <td>
                      {% if details.origin_info %}
                          <a href="{% url 'multiplicity:place' details.origin_info.city.slug details.origin_info.slug %}" title="Type: {{details.origin_info.type.name }}. City: {{details.origin_info.city.name }}">{{ details.origin }}</a>
                      {% else %}
                          <span class="dottedline new">{{ details.origin }}</span>
                      {% endif %}
                  </td>
              {% endif %}
              {% if show_destination %}
                  <td>
                      {% if details.destination_info %}
                          <a href="">{{ details.destination }}</a>
                      {% else %}
                          <span class="dottedline new">{{ details.destination }}</span>
                      {% endif %}
                  </td>
              {% endif %}
              {% if show_concentration %}
                  <td>{{ details.concentration }} {{ details.concentrationunit }}</td>
              {% endif %}
              {% if show_subset %}
                  <td>{{ details.subset }}</td>
              {% endif %}
            </tr>
          {% endfor %}
          </tbody>
        </table>

  </div>
</div>
    

{% endblock %}

{% block head %}
<style type="text/css">
.form-group .col-sm-10 strong{position:relative;top:5px}
.date, .dottedline{  border-bottom: 1px dashed #999;}
.new{font-weight:bold;color:#52cb52}
.new.dottedline{border-color:#52cb52}
</style>
{% endblock %}

{% block sidebar %}
{% include 'multiplicity/sidebar.default.html' %}

{% endblock %}

{% block pagehead %}
<div id="page-head">
    
    <div id="page-title">
        <h1 class="page-header text-overflow">{{ info.name }}</h1>
    </div>

    <ol class="breadcrumb">
        <li><a href="/"><i class="pli-home"></i></a></li>
        <li><a href="{% url 'staf:index' %}">Data</a></li>
        <li><a href="{% url 'staf:datasets' %}">Datasets</a></li>
        <li><a href="{% url 'staf:dataset' info.id %}">{{ info.name }}</a></li>
        <li><a href="{% url 'staf:flows' info.id %}">Flows</a></li>
        {% if flow.id %}
          <li><a href="{% url 'staf:flow' info.id flow.id %}">{{ flow.name }}</a></li>
          <li class="active">Manage data</li>
        {% else %}
          <li class="active">Add flow</li>
        {% endif %}
    </ol>

</div>

{% endblock %}

{% block footer %}

{% endblock %}

src/templates/staf/index.html
{% extends 'multiplicity/base.html' %}
{% load static %}

{% block title %}Data{% endblock %}
{% block container %}stretch-bg-head{% endblock %}

{% block content %}


<div class="panel">
  <div class="panel-heading">
      <h3 class="panel-title">Data</h3>
  </div>
  <div class="panel-body">

    <p>This page contains links to StafDB related pages. This section is not currently linked anywhere publicly but can 
    be used to see different components of StafDB:</p>

    <ul>
      <li><a href="{% url 'staf:materials' %}">Materials</a></li>
      <li><a href="{% url 'staf:processes' %}">Processes: tree</a></li>
      <li><a href="{% url 'staf:processlisting' %}">Processes: browser</a></li>
      <li><a href="{% url 'staf:processtable' %}">Processes: full search table</a></li>
      <li><a href="{% url 'staf:processgroups' %}">Process groups</a></li>
      <li><a href="{% url 'staf:units' %}">Units</a></li>
      <li><a href="{% url 'staf:search' %}">Search</a></li>
    </ul>

  </div>
</div>
    

{% endblock %}

{% block head %}
{% endblock %}

{% block sidebar %}
{% include 'multiplicity/sidebar.default.html' %}

{% endblock %}

{% block pagehead %}
<div id="page-head">
    
    <div id="page-title">
        <h1 class="page-header text-overflow">Data</h1>
    </div>

    <ol class="breadcrumb">
        <li><a href="/"><i class="pli-home"></i></a></li>
        <li class="active">Data</li>
    </ol>

</div>

{% endblock %}

{% block footer %}

{% endblock %}

src/templates/staf/material.list.html
{% extends 'multiplicity/base.html' %}
{% load static %}

{% block title %}Urban metabolism data{% endblock %}
{% block container %}stretch-bg-head{% endblock %}

{% block content %}


<div class="panel">
  <div class="panel-heading">
      <h3 class="panel-title">Materials</h3>
  </div>
  <div class="panel-body">

  <div id="tree"></div>
  <div id="details"></div>

  </div>
</div>
    

{% endblock %}

{% block head %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/mar10/fancytree@2/dist/skin-lion/ui.fancytree.min.css" />
<style type="text/css">
#tree{overflow:hidden}
#details{margin-top:20px}
</style>
{% endblock %}

{% block sidebar %}
{% include 'multiplicity/sidebar.default.html' %}

{% endblock %}

{% block pagehead %}
<div id="page-head">
    
    <div id="page-title">
        <h1 class="page-header text-overflow">Urban metabolism data</h1>
    </div>

    <ol class="breadcrumb">
        <li><a href="/"><i class="pli-home"></i></a></li>
        <li><a href="{% url 'staf:index' %}">Data</a></li>
        <li class="active">Materials</li>
    </ol>

</div>

{% endblock %}

{% block footer %}
<script type="text/javascript" src="https://cdn.jsdelivr.net/gh/mar10/fancytree@2/dist/jquery.fancytree-all-deps.min.js"></script>
<script type="text/javascript">
$(function(){
    // Load tree from Ajax JSON
    $("#tree").fancytree({
      source: 
        [
          {% for details in materials %}
            {title: "{{ details.code }} - {{ details.name }}", key: "{{ details.id }}", lazy: true},
          {% endfor %}
        ]
      ,
			lazyLoad: function(event, data){
        var node = data.node;
				data.result = $.ajax({
					url: "{% url 'staf:materialajax' %}",
					dataType: "json",
          data: {mode: "children", parent: node.key},
				});
			},
      activate: function(event, data) {
        var node = data.node;
        var settext = node.title+'<br> <br><a class="btn btn-warning" href="/data/materials/'+node.key+'/edit"><i class="fa fa-pencil-alt"></i> Edit</a> <a class="btn btn-info" href="/data/materials/'+node.key+'/child"><i class="fa fa-plus"></i> Add child</a>';
        $("#details").html(settext);
      },
		});
    
});

</script>
{% endblock %}

src/templates/staf/materialform.html
{% extends 'multiplicity/base.html' %}
{% load bootstrap3 %}
{% load static %}

{% block title %}{% if info.id %}{{ info.name }} | Edit material{% else %}Create material{% endif %}{% endblock %}
{% block container %}stretch-bg-head{% endblock %}

{% block content %}


<div class="panel">
  <div class="panel-heading">

    <h3 class="panel-title">Materials</h3>

  </div>
  <div class="panel-body">

  {% if success %}
    <div class="alert alert-success">
      <p>
      Information was saved.
      <span class="text-right">{% now "r" %}</span>
      </p>
      <p>
        <a href="{% url 'staf:material_child' parent.id %}" class="btn btn-default">Add another child to {{ parent.name }}</a>
      </p>
    </div>
  {% endif %}

  {% if parent.id %}

    <div class="alert alert-warning">
      You are adding a child to: <strong>{{ parent.code }} - {{ parent.name }}</strong>
    </div>

  {% endif %}

    <form action="" method="post" class="form form-horizontal">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% buttons submit='Save' layout='horizontal' %}{% endbuttons %}
    </form>


  </div>
</div>
    

{% endblock %}

{% block head %}
{% endblock %}

{% block sidebar %}
{% include 'multiplicity/sidebar.default.html' %}

{% endblock %}

{% block pagehead %}
<div id="page-head">
    
    <div id="page-title">
        <h1 class="page-header text-overflow">{% if info.id %}{{ info.name }} | Edit material{% else %}Create material{% endif %}</h1>
    </div>

    <ol class="breadcrumb">
        <li><a href="/"><i class="pli-home"></i></a></li>
        <li><a href="{% url 'staf:index' %}">Data</a></li>
        <li><a href="{% url 'staf:materials' %}">Materials</a></li>
        {% if info.id %}
          <li class="active">Edit material</li>
        {% else %}
          <li class="active">Create material</li>
        {% endif %}
    </ol>

</div>

{% endblock %}

{% block footer %}

{% endblock %}

src/templates/staf/process.browser.html
{% extends 'multiplicity/base.html' %}
{% load static %}

{% block title %}Urban metabolism data: Processes{% endblock %}
{% block container %}stretch-bg-head{% endblock %}

{% block content %}


<div class="panel">
  <div class="panel-heading">
      <h3 class="panel-title">Processes</h3>
  </div>
  <div class="panel-body">

    <ol class="breadcrumb">
        {% if home %}
            <li class="active">Processes</li>
        {% else %}
            <li><a href="{% url 'staf:processes' %}">Processes</a></li>
            {% for details in ancestors %}
                <li><a href="{% url 'staf:processlisting' details.id %}">{{ details.name}}</a></li>
            {% endfor %}
            <li class="active">{{ info.name }}</li>
        {% endif %}

    </ol>


  <table class="table table-striped">
    <tr>
      <th>Code</th>
      <th>Process</th>
    </tr>
    {% for details in processes %}
      <tr>
        <td>{{ details.code }}</td>
        <td><a href="{% url 'staf:processlisting' details.id %}">{{ details.name }}</a></td>
      </tr>
    {% endfor %}
  </table>

  <p><a href="{% url 'staf:processes' %}" class="btn btn-info">View process tree</a></p>

  </div>
</div>
    

{% endblock %}

{% block head %}
{% endblock %}

{% block sidebar %}
{% include 'multiplicity/sidebar.default.html' %}

{% endblock %}

{% block pagehead %}
<div id="page-head">
    
    <div id="page-title">
        <h1 class="page-header text-overflow">Urban metabolism data</h1>
    </div>

    <ol class="breadcrumb">
        <li><a href="/"><i class="pli-home"></i></a></li>
        <li><a href="{% url 'staf:index' %}">Data</a></li>
        <li class="active">Processes</li>
    </ol>

</div>

{% endblock %}

{% block footer %}

{% endblock %}

src/templates/staf/process.table.html
{% extends 'multiplicity/base.html' %}
{% load static %}

{% block title %}Urban metabolism data: Processes{% endblock %}
{% block container %}stretch-bg-head{% endblock %}

{% block content %}


<div class="panel">
  <div class="panel-heading">
      <h3 class="panel-title">Processes</h3>
  </div>
  <div class="panel-body">

    <ol class="breadcrumb">
        <li class="active">Processes</li>
    </ol>


  <table class="table table-striped datatable">
    <thead>
    <tr>
      <th colspan="2">Code</th>
      <th>Process</th>
    </tr>
    </thead>
    <tbody>
    {% for details in processes %}
      <tr>
        <td><a href="{% url 'staf:process_edit' details.id %}"><i class="fas fa-pencil"></i></a></td>
        <td>{{ details.code }}</td>
        <td><a href="{% url 'staf:processlisting' details.id %}">{{ details.name }}</a></td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

  <p><a href="{% url 'staf:processes' %}" class="btn btn-info">View process tree</a></p>

  </div>
</div>
    

{% endblock %}

{% block head %}
{% endblock %}

{% block sidebar %}
{% include 'multiplicity/sidebar.default.html' %}

{% endblock %}

{% block pagehead %}
<div id="page-head">
    
    <div id="page-title">
        <h1 class="page-header text-overflow">Urban metabolism data</h1>
    </div>

    <ol class="breadcrumb">
        <li><a href="/"><i class="pli-home"></i></a></li>
        <li><a href="{% url 'staf:index' %}">Data</a></li>
        <li class="active">Processes</li>
    </ol>

</div>

{% endblock %}

{% block footer %}

{% endblock %}

src/templates/staf/processform.html
{% extends 'multiplicity/base.html' %}
{% load bootstrap3 %}
{% load static %}

{% block title %}{% if info.id %}{{ info.name }} | Edit process{% else %}Create process{% endif %}{% endblock %}
{% block container %}stretch-bg-head{% endblock %}

{% block content %}


<div class="panel">
  <div class="panel-heading">

    <h3 class="panel-title">Processes</h3>

  </div>
  <div class="panel-body">

  {% if success %}
    <div class="alert alert-success">
      <p>
      Information was saved.
      <span class="text-right">{% now "r" %}</span>
      </p>
      <p>
        <a href="{% url 'staf:process_child' parent.id %}" class="btn btn-default">Add another child to {{ parent.name }}</a>
      </p>
    </div>
  {% endif %}

  {% if parent.id %}

    <div class="alert alert-warning">
      You are adding a child to: <strong>{{ parent.code }} - {{ parent.name }}</strong>
    </div>

  {% endif %}

    <form action="" method="post" class="form form-horizontal">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% buttons submit='Save' layout='horizontal' %}{% endbuttons %}
    </form>


  </div>
</div>
    

{% endblock %}

{% block head %}
{% endblock %}

{% block sidebar %}
{% include 'multiplicity/sidebar.default.html' %}

{% endblock %}

{% block pagehead %}
<div id="page-head">
    
    <div id="page-title">
        <h1 class="page-header text-overflow">{% if info.id %}{{ info.name }} | Edit process{% else %}Create process{% endif %}</h1>
    </div>

    <ol class="breadcrumb">
        <li><a href="/"><i class="pli-home"></i></a></li>
        <li><a href="{% url 'staf:index' %}">Data</a></li>
        <li><a href="{% url 'staf:processes' %}">Processes</a></li>
        {% if info.id %}
          <li class="active">Edit process</li>
        {% else %}
          <li class="active">Create process</li>
        {% endif %}
    </ol>

</div>

{% endblock %}

{% block footer %}

{% endblock %}