src/ie/urls.py
from django.urls import include, path
from django.contrib import admin

" These two are to make file uploads work "
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('data/', include('staf.urls')),
    path('intranet/', include('team.urls')),
    path('', include('core.urls')),
    path('cities/', include('multiplicity.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/multiplicity/urls.py
from django.urls import path

from . import views

app_name = 'multiplicity'
urlpatterns = [

    # Admin

    path('admin/locations/', views.admin_locations, name='admin_locations'),
    path('admin/locations/<int:id>/', views.admin_location, name='admin_location'),
    path('admin/locations/create/', views.admin_location, name='admin_location_create'),

    path('admin/referencespaces/<slug:type>/', views.admin_referencespaces, name='admin_referencespaces'),
    path('admin/referencespaces/<slug:type>/<int:id>/', views.admin_referencespace, name='admin_referencespace'),
    path('admin/referencespaces/<slug:type>/<int:referencespace>/location/', views.admin_location, name='admin_referencespace_location'),
    path('admin/referencespaces/<slug:type>/create/', views.admin_referencespace, name='admin_referencespace_create'),

    path('admin/<slug:city>/overview/', views.admin_data_overview, name='admin_data_overview'),
    path('admin/overview/', views.admin_data_overview_all, name='admin_data_overview_all'),
    path('admin/<slug:city>/sector/<slug:sector>/activate/', views.admin_activate_sector, name='admin_activate_sector'),
    path('admin/<slug:city>/sector/<slug:sector>/deactivate/', views.admin_deactivate_sector, name='admin_deactivate_sector'),

    path('admin/datasettype/', views.admin_datasettypes, name='admin_datasettypes'),
    path('admin/datasettype/<int:id>/', views.admin_datasettype, name='admin_datasettype'),
    path('admin/datasettype/create/', views.admin_datasettype, name='admin_datasettype'),

    path('admin/referencephotos/', views.admin_referencephoto, name='admin_referencephotos'),
    path('admin/referencephotos/<int:id>/', views.admin_referencephoto, name='admin_referencephoto'),
    path('admin/referencephotos/create/', views.admin_referencephoto, name='admin_referencephoto'),
    path('admin/<slug:city>/mtu/<int:mtu>/delete/', views.admin_mtu_delete, name='admin_mtu_delete'),

    # General
    path('datasets/', views.datasets_all, name='datasets_all'),
    path('table/datasets/<int:dataset>/', views.datatable, name='datatable_dataset'),
    path('<slug:city>/checklist/', views.checklist, name='checklist'),

    path('', views.index, name='index'),
    path('<slug:city>/research/', views.research, name='research'),

    #path('<slug:city>/material-stocks/<slug:type>', views.flow, name='stock'),

    path('<slug:city>/material-flows/<slug:topic>/', views.datasets_overview, name='flows'),
    path('<slug:city>/material-stocks/<slug:topic>/', views.datasets_overview, {'type': 'stocks' }, name='stocks'),
    path('<slug:city>/energy-flows/<slug:topic>/', views.datasets_overview, {'type': 'energy'}, name='energy_flows'),

    #path('<slug:city>/material-flows/<slug:slug>', views.overview, name='overview_flows'),
    #path('<slug:city>/material-flows/<slug:slug>/<slug:type>', views.flow, name='flow'),
    #path('<slug:city>/material-stocks', views.overview, {'slug': 'material-stocks' }, name='overview_stocks'),

    path('<slug:city>/profile/<slug:topic>/', views.topic, name='topic'),
    #path('<slug:city>/<slug:topic>', views.topic, name='topic'),

    path('<slug:city>/maps/', views.map, name='map'),
    path('<slug:city>/maps/mtu/', views.mtu_map, name='map_mtu'),
    path('<slug:city>/maps/infrastructure/', views.map_infrastructure, name='map_infrastructure'),
    path('<slug:city>/maps/other/', views.photos, {'type': 'map'}, name='map_other'),
    path('<slug:city>/maps/<slug:type>/', views.map, name='map'),
    path('<slug:city>/mtu/<slug:type>/<slug:space>/', views.space, name='mtu_space'),
    path('<slug:city>/maps/mtu/<slug:type>/', views.mtu_map, name='map_mtu'),
    path('<slug:city>/maps/mtu/<slug:type>/download/', views.download_mtu, name='download_mtu'),
    path('<slug:city>/maps/boundaries/<int:id>/', views.map, name='map'),
    path('<slug:city>/maps/boundaries/<int:id>/download/', views.download_location, name='download_location'),
    path('<slug:city>/datasets/', views.datasets, name='datasets'),
    path('<slug:city>/resources/photos/', views.photos, name='photos'),
    path('<slug:city>/resources/videos/', views.videos, name='videos'),
    path('<slug:city>/resources/links/', views.topic, {'topic': 'links'}, name='links'),
    path('<slug:city>/resources/<slug:slug>/', views.resources, name='resources'),
    path('<slug:city>/datasets/<int:id>/', views.dataset, name='dataset'),
    path('<slug:city>/download/csv/<int:id>/', views.download_csv, name='download_csv'),
    path('<slug:city>/datasets/<int:id>/delete/', views.delete_dataset, name='delete_dataset'),
    path('<slug:city>/datasets/<int:id>/reset/', views.reset_dataset, name='reset_dataset'),
    path('<slug:city>/datasets/<int:dataset>/graph/<int:id>/', views.graph, name='graph'),
    path('<slug:city>/datasets/<int:dataset>/graph/<int:id>/space/<int:space>/', views.graph, name='graph'),
    path('<slug:city>/datasets/<int:id>/<slug:slug>/', views.dataset, name='dataset_slice'),
    path('<slug:city>/information/', views.information_form, name='information_form'),
    path('<slug:city>/information/topic/<int:topic>/', views.information_form, name='information_form_topic'),
    path('<slug:city>/information/<int:id>/', views.information_form, name='information_form'),
    path('<slug:city>/map/', views.photo_form, {'map': True}, name='map_form'),
    path('<slug:city>/sectors/<slug:sector>/', views.sector, name='sector'),

    # Downloading data
    path('<slug:city>/download/', views.download, name='download'),

    # Uploading data
    path('<slug:city>/upload/', views.upload, name='upload'),

    # Uploading infrastructure data
    path('<slug:city>/upload/infrastructure/', views.upload_infrastructure, name='upload_infrastructure'),
    path('<slug:city>/upload/infrastructure/<slug:type>/', views.upload_infrastructure_file, name='upload_infrastructure_file'),
    path('<slug:city>/upload/infrastructure/<slug:type>/sample/', views.upload_infrastructure_file_sample, name='upload_infrastructure_file_sample'),
    path('<slug:city>/upload/infrastructure/<slug:type>/<int:id>/', views.upload_infrastructure_review, name='upload_infrastructure_review'),
    path('<slug:city>/upload/infrastructure/<slug:type>/<int:id>/meta/', views.upload_infrastructure_meta, name='upload_infrastructure_meta'),

    # Uploading flows/stocks data
    path('<slug:city>/upload/flow/', views.upload_flow, name='upload_flow'),
    path('<slug:city>/upload/flow/<int:id>/', views.upload_flow_file, name='upload_flow_file'),
    path('<slug:city>/upload/flow/<int:id>/sample/', views.upload_flow_file_sample, name='upload_flow_file_sample'),
    path('<slug:city>/upload/flow/<int:type>/<int:id>/update/<int:update>/', views.upload_flow_review, name='upload_flow_review'),
    path('<slug:city>/upload/flow/<int:type>/<int:id>/', views.upload_flow_review, name='upload_flow_review'),
    path('<slug:city>/upload/flow/<int:type>/<int:id>/meta/', views.upload_flow_meta, name='upload_flow_meta'),
    path('<slug:city>/upload/stock/', views.upload_flow, {'type': 'stocks'}, name='upload_stock'),

    # Uploading reference
    path('<slug:city>/upload/resources/<int:type>/', views.reference_form, name='reference_form'),

    # Uploading geospatial data
    path('<slug:city>/upload/systemboundaries/', views.upload_systemboundaries, name='upload_systemboundaries'),
    path('<slug:city>/upload/systemboundaries/create/', views.upload_systemboundary, name='upload_systemboundary'),
    path('<slug:city>/upload/systemboundaries/<int:location>/', views.upload_systemboundary, name='upload_systemboundary'),

    path('<slug:city>/upload/mtu/', views.upload_mtu, name='upload_mtu'),
    path('<slug:city>/upload/mtu/<slug:filename>/', views.upload_mtu_review, name='upload_mtu_review'),

    # Uploading multimedia
    path('<slug:city>/photo/', views.photo_form, name='photo_form'),
    path('<slug:city>/photo/<int:id>/', views.photo_form, name='photo_form'),

    path('<slug:city>/upload/video/', views.upload_video, name='upload_video'),
    path('<slug:city>/upload/video/<int:id>/', views.upload_video, name='upload_video'),

    path('<slug:city>/infrastructure/<slug:type>/<slug:space>/', views.space, name='space'),
    path('<slug:city>/infrastructure/<slug:type>/', views.space_list, name='space_list'),
    path('<slug:city>/infrastructure/<slug:topic>/', views.infrastructure_list, name='infrastructure_list'),
    path('<slug:city>/infrastructure/', views.infrastructure_list, name='infrastructure_list'),

    path('<slug:city>/<slug:main>/<slug:topic>/', views.topic, name='subtopic'),
    path('<slug:city>/<slug:main>/<slug:topic>/input/', views.topic, {'tab': 'input'}, name='subtopic_input'),
    path('<slug:city>/<slug:main>/<slug:topic>/use/', views.topic, {'tab': 'use' }, name='subtopic_use'),
    path('<slug:city>/<slug:main>/<slug:topic>/output/', views.topic, {'tab': 'output'}, name='subtopic_output'),
    #path('<slug:city>/<slug:theme>/<slug:topic>/<slug:type>', views.space_list, name='space_list'),

    # This view is used to show the content of a slide, when recording a video
    path('<slug:city>/slide/', views.temp_slide, name='temp_slide'),

    path('materials/', views.materials, name='materials'),
    path('materials/<slug:catalog>/', views.materials, name='materials'),
    path('<slug:slug>/', views.index, name='city'),
    #path('profile', views.detail, name='profile'),

    # AJAX
    path('search/ajax', views.referencespace_search_ajax, name='referencespace_search_ajax'),

]

src/team/urls.py
from django.urls import path
from django.contrib.auth import urls
from django.conf.urls import include

from . import views

app_name = 'team'

urlpatterns = [
    path('', views.index, name='homepage'),
    path('controlpanel', views.controlpanel, name='controlpanel'),
    path('category/<int:id>', views.category),
    path('taskforce/<int:id>', views.taskforce, name='taskforce'),
    path('taskforce/<int:category>/task', views.ticket, name='newticket'),
    path('taskforce/<int:id>/leave', views.leavetaskforce, name='leavetaskforce'),
    path('tickets', views.ticketlist, name='tickets'),
    path('tickets/<int:id>', views.ticketdetails, name='ticket'),
    path('tickets/<int:id>/status/<slug:status>', views.ticketstatus, name='ticketstatus'),
    path('tickets/<int:id>/startdiscussion', views.ticketdiscussion, name='ticketdiscussion'),
    path('tickets/<int:id>/progress', views.ticketprogress, name='ticketprogress'),
    path('tickets/<int:id>/assign_to/<int:person>', views.ticketperson, name='ticketperson'),
    path('tickets/<int:id>/edit', views.ticket, name='editticket'),
    path('category/<int:id>/view', views.opencategory, name='viewcategory'),
    path('category/<int:id>/config', views.categoryconfig, name='categoryconfig'),
    path('category/<int:id>/config/save', views.saveconfig, name='saveconfig'),
    path('category/<int:id>/<int:topic>', views.category),
    path('topic/<int:id>', views.topic),
    path('topic/<int:id>/view', views.opentopic, name='topic'),
    path('topic/<int:id>/subscription/<slug:type>', views.subscribetopic, name='topic_subscribe'),
    path('topic/<int:id>/edit', views.edittopic, name='edittopic'),
    path('topic/create', views.createtopic, name='createtopic'),
    path('topic/<int:id>/message', views.createmessage),
    path('message/<int:id>/delete', views.deletemessage, name='deletemessage'),
    path('register', views.register),
    path('taskforces', views.taskforces, name='taskforces'),
    path('search', views.search, name='search'),
    path('profile', views.profile, name='memberprofile'),
    path('profile/save', views.saveprofile, name='saveprofile'),
    path('reports/tickets', views.ticketreport, name='ticketreport'),
    path('projects', views.projects, name='projects'),
    path('projects/<int:id>', views.project, name='project'),
    path('projects/create', views.project, name='createproject'),
]

src/templates/multiplicity/admin/overview.data.all.html
{% extends 'multiplicity/base.html' %}
{% load static %}

{% block title %}Data overview{% endblock %}
{% block container %}stretch-bg-head{% endblock %}

{% block content %}

<ol class="breadcrumb">
  <li><a href="./"><i class="pli-home"></i></a></li>
  <li><a href="{% url 'team:controlpanel' %}">Back-end</a></li>
  <li class="active">Data overview</li>
</ol>

<div class="row">
  <div class="col">
    <div class="panel">
      <div class="panel-body">
        <h3>Datasets</h3>
        <table class="table table-striped datatable">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>City</th>
                    <th>User</th>
                    <th>Creation date</th>
                </tr>
            </thead>
            <tbody>
            {% for details in datasets %}
                <tr>
                    <td>{{ details.id }}. <a href="{% url 'multiplicity:dataset' details.primary_space.slug details.id %}">{{ details.name }}</a></td>
                    <td>{{ details.primary_space.name }}</td>
                    <td>
                      {% for csv in details.csv_set.all %}
                        {{ csv.user }}<br>
                      {% endfor %}
                    </td>
                    <td>
                      {% for csv in details.csv_set.all %}
                        {{ csv.created_at|date:"M d, Y H:i" }}<br>
                      {% endfor %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col">
    <div class="panel">
      <div class="panel-body">
        <h3>CSV Files - datasets</h3>
        <table class="table table-striped datatable">
            <thead>
                <tr>
                    <th>Creation date</th>
                    <th>Name</th>
                    <th>User</th>
                    <th>Dataset</th>
                    <th>Type</th>
                </tr>
            </thead>
            <tbody>
            {% for details in csv %}
                <tr>
                    <td data-sort="{{ details.created_at|date:"Y-m-d H:i" }}">{{ details.created_at }}</td>
                    <td>
                      <a href="{% url 'multiplicity:download_csv' details.space.slug details.id %}"><i class="fa fa-download"></i></a>
                      <a href="{% url 'multiplicity:upload_flow_review' details.space.slug details.datasettype.id details.id %}">{{ details.original_name }}</a>
                    </td>
                    <td><a href="{% url 'core:userdetails' details.user.id %}">{{ details.user.first_name }} {{ details.user.last_name }}</a></td>
                    <td>
                    {% if details.dataset %}
                      <a href="{% url 'multiplicity:dataset' details.space.slug details.dataset.id %}">#{{ details.dataset.id }}</a>
                    {% endif %}
                    </td>
                    <td>{{ details.datasettype.name }}<br>
                    {{ details.space.name }}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col">
    <div class="panel">
      <div class="panel-body">
        <h3>CSV Files - reference spaces</h3>
        <table class="table table-striped datatable">
            <thead>
                <tr>
                    <th>Creation date</th>
                    <th>Name</th>
                    <th>User</th>
                    <th>Import?</th>
                    <th>Type</th>
                </tr>
            </thead>
            <tbody>
            {% for details in space_csv %}
                <tr>
                    <td data-sort="{{ details.created_at|date:"Y-m-d H:i" }}">{{ details.created_at }}</td>
                    <td><a href="{% url 'multiplicity:upload_infrastructure_review' details.space.slug details.type.slug details.id %}">{{ details.original_name }}</a></td>
                    <td><a href="{% url 'core:userdetails' details.user.id %}">{{ details.user.first_name }} {{ details.user.last_name }}</a></td>
                    <td>
                    {% if details.imported %}
                      Yes
                    {% endif %}
                    </td>
                    <td>{{ details.type.name }}<br>{{ details.space.name }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col">
    <div class="panel">
      <div class="panel-body">
        <h3>Information</h3>

        <table class="table table-striped datatable">
          <thead>
            <tr>
              <th>Information</th>
              <th>City</th>
            </tr>
          </thead>
          <tbody>
            {% for details in information %}
              <tr>
                <td><a href="{% url 'multiplicity:information_form' details.space.slug details.id %}">{{ details.title }}</a></td>
                <td>{{ details.space.name }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

{% endblock %}

{% block head %}
<style type="text/css">
textarea.form-control{height:200px}

#gallery figure {
  position:relative;
}
#gallery figure span {
  position: absolute;
  top: 10px;
  right: 15px;
  opacity:0.7;
}

#gallery figure.fade {
  opacity: 0.6;
}
#gallery .fade img {
  border: 2px solid #f00;
}
</style>
{% endblock %}

{% block sidebar %}
{% include 'multiplicity/sidebar.default.html' %}

{% endblock %}

{% block footer %}

{% endblock %}

src/templates/multiplicity/admin/overview.data.html
{% extends 'multiplicity/base.html' %}
{% load static %}

{% block title %}{{ info.name }} | {{ info.country }}{% endblock %}
{% block container %}stretch-bg-head{% endblock %}

{% block content %}

<ol class="breadcrumb">
  <li><a href="./"><i class="pli-home"></i></a></li>
  <li><a href="{% url 'team:controlpanel' %}">Back-end</a></li>
  <li><a href="{% url 'multiplicity:admin_referencespaces' info.type.slug %}">{{ info.type.name }}</a></li>
  <li>{{ info.name }}</li>
  <li class="active">Data overview</li>
</ol>

<div class="row">
  <div class="col">
    <div class="panel">
      <div class="panel-body">
        <p><a href="{% url 'multiplicity:city' info.slug %}" class="btn btn-info">View {{ info.name }} online</a></p>
        <h3>Sectors</h3>
        <table class="table table-striped">
          <tr>
            <th>Sector</th>
            <th>Action</th>
            <th>View</th>
          </tr>
        {% for sector in sectors %}
          <tr>
            <td>{{ sector }}</td>
            <td>
            {% if sector.id in active_sectors %}
              <a href="{% url 'multiplicity:admin_deactivate_sector' info.slug sector.slug %}">deactivate</a>
            {% else %}
              <a href="{% url 'multiplicity:admin_activate_sector' info.slug sector.slug %}">activate</a>
            {% endif %}
            </td>
            <td>
              <a href="{% url 'multiplicity:sector' info.slug sector.slug %}">View</a>
            </td>
          </tr>
        {% endfor %}
        </table>


      </div>
    </div>
  </div>
</div>

{% if datasets %}

<div class="row">
  <div class="col">
    <div class="panel">
      <div class="panel-body">
        <h3>Datasets</h3>
        <table class="table table-striped datatable">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Process</th>
                    <th>User</th>
                    <th>Creation date</th>
                </tr>
            </thead>
            <tbody>
            {% for details in datasets %}
                <tr>
                    <td>{{ details.id }}. <a href="{% url 'multiplicity:dataset' info.slug details.id %}">{{ details.name }}</a></td>
                    <td>{{ details.process.name|lower|capfirst }}</td>
                    <td>
                      {% for csv in details.csv_set.all %}
                        {{ csv.user }}<br>
                      {% endfor %}
                    </td>
                    <td>
                      {% for csv in details.csv_set.all %}
                        {{ csv.created_at|date:"M d, Y H:i" }}<br>
                      {% endfor %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

{% endif %}

{% if csv %}

<div class="row">
  <div class="col">
    <div class="panel">
      <div class="panel-body">
        <h3>CSV Files - datasets</h3>
        <table class="table table-striped datatable">
            <thead>
                <tr>
                    <th>Creation date</th>
                    <th>Name</th>
                    <th>User</th>
                    <th>Dataset</th>
                    <th>Type</th>
                </tr>
            </thead>
            <tbody>
            {% for details in csv %}
                <tr>
                    <td data-sort="{{ details.created_at|date:"Y-m-d H:i" }}">{{ details.created_at }}</td>
                    <td>
                      <a href="{% url 'multiplicity:download_csv' info.slug details.id %}"><i class="fa fa-download"></i></a>
                      <a href="{% url 'multiplicity:upload_flow_review' info.slug details.datasettype.id details.id %}">{{ details.original_name }}</a>
                    </td>
                    <td><a href="{% url 'core:userdetails' details.user.id %}">{{ details.user.first_name }} {{ details.user.last_name }}</a></td>
                    <td>
                    {% if details.dataset %}
                      <a href="{% url 'multiplicity:dataset' info.slug details.dataset.id %}">#{{ details.dataset.id }}</a>
                    {% endif %}
                    </td>
                    <td>{{ details.datasettype.name }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

{% endif %}

{% if space_csv %}

<div class="row">
  <div class="col">
    <div class="panel">
      <div class="panel-body">
        <h3>CSV Files - reference spaces</h3>
        <table class="table table-striped datatable">
            <thead>
                <tr>
                    <th>Creation date</th>
                    <th>Name</th>
                    <th>User</th>
                    <th>Import?</th>
                    <th>Type</th>
                </tr>
            </thead>
            <tbody>
            {% for details in space_csv %}
                <tr>
                    <td data-sort="{{ details.created_at|date:"Y-m-d H:i" }}">{{ details.created_at }}</td>
                    <td><a href="{% url 'multiplicity:upload_infrastructure_review' info.slug details.type.slug details.id %}">{{ details.original_name }}</a></td>
                    <td><a href="{% url 'core:userdetails' details.user.id %}">{{ details.user.first_name }} {{ details.user.last_name }}</a></td>
                    <td>
                    {% if details.imported %}
                      Yes
                    {% endif %}
                    </td>
                    <td>{{ details.type.name }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

{% endif %}

{% if information %}

<div class="row">
  <div class="col">
    <div class="panel">
      <div class="panel-body">
        <h3>Information</h3>

        <ul>
          {% for details in information %}
            <li><a href="{% url 'multiplicity:information_form' info.slug details.id %}">{{ details.title }}</a></li>
          {% endfor %}
        </ul>
        
      </div>
    </div>
  </div>
</div>

{% endif %}

{% if mtu_list %}

<div class="row">
  <div class="col">
    <div class="panel">
      <div class="panel-body">
        <h3>MTU List</h3>
        <table class="table table-striped datatable">
            <thead>
              <tr>
                <th>Name</th>
                <th>Status</th>
                <th>Options</th>
              </tr>
            </thead>
            <tbody>
            {% for details in mtu_list %}
                <tr>
                  <td><a href="{% url 'multiplicity:map_mtu' info.slug details.type.slug %}">{{ details.type.name }}</a></td>
                  <td>{% if details.active %}Active{% else %}Inactive{% endif %}</td>
                  <td>{% if details.active %}<a href="{% url 'multiplicity:admin_mtu_delete' info.slug details.id %}" onclick="javascript:return confirm('Are you sure you want to deactivate all the MTUs in this category?')">Deactivate</a>{% endif %}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

{% endif %}

{% if spaces %}

<div class="row">
  <div class="col">
    <div class="panel">
      <div class="panel-body">
        <h3>Reference spaces</h3>
        <table class="table table-striped datatable">
            <thead>
              <tr>
                <th>Name</th>
                <th>Type</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
            {% for details in spaces %}
                <tr>
                  <td><a href="{% url 'multiplicity:space' info.slug details.type.slug details.slug %}">{{ details.name }}</a></td>
                  <td>{{ details.type.name }}</td>
                  <td>{% if details.active %}Active{% else %}Inactive{% endif %}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

{% endif %}

{% if photos %}

  <div class="panel" id="gallery">
    <div class="panel-body">
      <div class="row">
      <h3>Photos</h3>
      <p>Images with red borders are not shown in the galleries. The number indicates the order in which the images are shown.</p>
      {% for details in photos %}
        {% ifchanged details.process %}
          </div><div class="row">

            <h4 class="mar-top">
              {% if details.process %}
                {{ details.process.name|lower|capfirst }}
              {% else %}
                General photos
                <br>
                <span style="font-size:15px">The first photo in this list will be shown on the homepage</span>
              {% endif %}
            </h4>

        {% endifchanged %}

      <figure class="col-lg-2 col-md-3 col-sm-4 col-xs-6 single-photo {% if details.deleted %}fade{% endif %}">
        <a href="{% url 'multiplicity:photo_form' info.slug details.id %}"><img src="{{ details.image.thumbnail.url }}" alt="" /></a>
        <span class="badge badge-default">{{ details.position }}</span>
      </figure>
      {% endfor %}
      </div>
    </div>
  </div>

{% endif %}

<p><a href="{% url 'multiplicity:photo_form' info.slug %}">Add new photo</a></p>

{% if referencephotos %}

  <div class="panel">
    {% for details in referencephotos %}
      <a href="{% url 'multiplicity:photo_form' info.slug details.id %}"><img src="{{ details.image.thumbnail.url }}" alt="" /></a>
    {% endfor %}
  </div>

{% endif %}

<p><a href="{% url 'multiplicity:admin_referencephoto' %}">Add new reference photo</a></p>


{% endblock %}

{% block head %}
<style type="text/css">
textarea.form-control{height:200px}

#gallery figure {
  position:relative;
}
#gallery figure span {
  position: absolute;
  top: 10px;
  right: 15px;
  opacity:0.7;
}

#gallery figure.fade {
  opacity: 0.6;
}
#gallery .fade img {
  border: 2px solid #f00;
}
</style>
{% endblock %}

{% block sidebar %}
{% include 'multiplicity/sidebar.default.html' %}

{% endblock %}

{% block footer %}

{% endblock %}