src/ie/urls.py
from django.urls import include, path
from django.contrib import admin

" These two are to make file uploads work "
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('data/', include('staf.urls')),
    path('intranet/', include('team.urls')),
    path('', include('core.urls')),
    path('cities/', include('multiplicity.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/multiplicity/urls.py
from django.urls import path

from . import views

app_name = 'multiplicity'
urlpatterns = [

    # Admin

    path('admin/locations/', views.admin_locations, name='admin_locations'),
    path('admin/locations/<int:id>/', views.admin_location, name='admin_location'),
    path('admin/locations/create/', views.admin_location, name='admin_location_create'),

    path('admin/referencespaces/<slug:type>/', views.admin_referencespaces, name='admin_referencespaces'),
    path('admin/referencespaces/<slug:type>/<int:id>/', views.admin_referencespace, name='admin_referencespace'),
    path('admin/referencespaces/<slug:type>/<int:referencespace>/location/', views.admin_location, name='admin_referencespace_location'),
    path('admin/referencespaces/<slug:type>/create/', views.admin_referencespace, name='admin_referencespace_create'),

    path('admin/<slug:city>/overview/', views.admin_data_overview, name='admin_data_overview'),
    path('admin/overview/', views.admin_data_overview_all, name='admin_data_overview_all'),
    path('admin/<slug:city>/sector/<slug:sector>/activate/', views.admin_activate_sector, name='admin_activate_sector'),
    path('admin/<slug:city>/sector/<slug:sector>/deactivate/', views.admin_deactivate_sector, name='admin_deactivate_sector'),

    path('admin/datasettype/', views.admin_datasettypes, name='admin_datasettypes'),
    path('admin/datasettype/<int:id>/', views.admin_datasettype, name='admin_datasettype'),
    path('admin/datasettype/create/', views.admin_datasettype, name='admin_datasettype'),

    path('admin/referencephotos/', views.admin_referencephoto, name='admin_referencephotos'),
    path('admin/referencephotos/<int:id>/', views.admin_referencephoto, name='admin_referencephoto'),
    path('admin/referencephotos/create/', views.admin_referencephoto, name='admin_referencephoto'),
    path('admin/<slug:city>/mtu/<int:mtu>/delete/', views.admin_mtu_delete, name='admin_mtu_delete'),

    # General
    path('datasets/', views.datasets_all, name='datasets_all'),
    path('table/datasets/<int:dataset>/', views.datatable, name='datatable_dataset'),
    path('<slug:city>/checklist/', views.checklist, name='checklist'),

    path('', views.index, name='index'),
    path('<slug:city>/research/', views.research, name='research'),

    #path('<slug:city>/material-stocks/<slug:type>', views.flow, name='stock'),

    path('<slug:city>/material-flows/<slug:topic>/', views.datasets_overview, name='flows'),
    path('<slug:city>/material-stocks/<slug:topic>/', views.datasets_overview, {'type': 'stocks' }, name='stocks'),
    path('<slug:city>/energy-flows/<slug:topic>/', views.datasets_overview, {'type': 'energy'}, name='energy_flows'),

    #path('<slug:city>/material-flows/<slug:slug>', views.overview, name='overview_flows'),
    #path('<slug:city>/material-flows/<slug:slug>/<slug:type>', views.flow, name='flow'),
    #path('<slug:city>/material-stocks', views.overview, {'slug': 'material-stocks' }, name='overview_stocks'),

    path('<slug:city>/profile/<slug:topic>/', views.topic, name='topic'),
    #path('<slug:city>/<slug:topic>', views.topic, name='topic'),

    path('<slug:city>/maps/', views.map, name='map'),
    path('<slug:city>/maps/mtu/', views.mtu_map, name='map_mtu'),
    path('<slug:city>/maps/infrastructure/', views.map_infrastructure, name='map_infrastructure'),
    path('<slug:city>/maps/other/', views.photos, {'type': 'map'}, name='map_other'),
    path('<slug:city>/maps/<slug:type>/', views.map, name='map'),
    path('<slug:city>/mtu/<slug:type>/<slug:space>/', views.space, name='mtu_space'),
    path('<slug:city>/maps/mtu/<slug:type>/', views.mtu_map, name='map_mtu'),
    path('<slug:city>/maps/mtu/<slug:type>/download/', views.download_mtu, name='download_mtu'),
    path('<slug:city>/maps/boundaries/<int:id>/', views.map, name='map'),
    path('<slug:city>/maps/boundaries/<int:id>/download/', views.download_location, name='download_location'),
    path('<slug:city>/datasets/', views.datasets, name='datasets'),
    path('<slug:city>/resources/photos/', views.photos, name='photos'),
    path('<slug:city>/resources/videos/', views.videos, name='videos'),
    path('<slug:city>/resources/links/', views.topic, {'topic': 'links'}, name='links'),
    path('<slug:city>/resources/<slug:slug>/', views.resources, name='resources'),
    path('<slug:city>/datasets/<int:id>/', views.dataset, name='dataset'),
    path('<slug:city>/download/csv/<int:id>/', views.download_csv, name='download_csv'),
    path('<slug:city>/datasets/<int:id>/delete/', views.delete_dataset, name='delete_dataset'),
    path('<slug:city>/datasets/<int:id>/reset/', views.reset_dataset, name='reset_dataset'),
    path('<slug:city>/datasets/<int:dataset>/graph/<int:id>/', views.graph, name='graph'),
    path('<slug:city>/datasets/<int:dataset>/graph/<int:id>/space/<int:space>/', views.graph, name='graph'),
    path('<slug:city>/datasets/<int:id>/<slug:slug>/', views.dataset, name='dataset_slice'),
    path('<slug:city>/information/', views.information_form, name='information_form'),
    path('<slug:city>/information/topic/<int:topic>/', views.information_form, name='information_form_topic'),
    path('<slug:city>/information/<int:id>/', views.information_form, name='information_form'),
    path('<slug:city>/map/', views.photo_form, {'map': True}, name='map_form'),
    path('<slug:city>/sectors/<slug:sector>/', views.sector, name='sector'),

    # Downloading data
    path('<slug:city>/download/', views.download, name='download'),

    # Uploading data
    path('<slug:city>/upload/', views.upload, name='upload'),

    # Uploading infrastructure data
    path('<slug:city>/upload/infrastructure/', views.upload_infrastructure, name='upload_infrastructure'),
    path('<slug:city>/upload/infrastructure/<slug:type>/', views.upload_infrastructure_file, name='upload_infrastructure_file'),
    path('<slug:city>/upload/infrastructure/<slug:type>/sample/', views.upload_infrastructure_file_sample, name='upload_infrastructure_file_sample'),
    path('<slug:city>/upload/infrastructure/<slug:type>/<int:id>/', views.upload_infrastructure_review, name='upload_infrastructure_review'),
    path('<slug:city>/upload/infrastructure/<slug:type>/<int:id>/meta/', views.upload_infrastructure_meta, name='upload_infrastructure_meta'),

    # Uploading flows/stocks data
    path('<slug:city>/upload/flow/', views.upload_flow, name='upload_flow'),
    path('<slug:city>/upload/flow/<int:id>/', views.upload_flow_file, name='upload_flow_file'),
    path('<slug:city>/upload/flow/<int:id>/sample/', views.upload_flow_file_sample, name='upload_flow_file_sample'),
    path('<slug:city>/upload/flow/<int:type>/<int:id>/update/<int:update>/', views.upload_flow_review, name='upload_flow_review'),
    path('<slug:city>/upload/flow/<int:type>/<int:id>/', views.upload_flow_review, name='upload_flow_review'),
    path('<slug:city>/upload/flow/<int:type>/<int:id>/meta/', views.upload_flow_meta, name='upload_flow_meta'),
    path('<slug:city>/upload/stock/', views.upload_flow, {'type': 'stocks'}, name='upload_stock'),

    # Uploading reference
    path('<slug:city>/upload/resources/<int:type>/', views.reference_form, name='reference_form'),

    # Uploading geospatial data
    path('<slug:city>/upload/systemboundaries/', views.upload_systemboundaries, name='upload_systemboundaries'),
    path('<slug:city>/upload/systemboundaries/create/', views.upload_systemboundary, name='upload_systemboundary'),
    path('<slug:city>/upload/systemboundaries/<int:location>/', views.upload_systemboundary, name='upload_systemboundary'),

    path('<slug:city>/upload/mtu/', views.upload_mtu, name='upload_mtu'),
    path('<slug:city>/upload/mtu/<slug:filename>/', views.upload_mtu_review, name='upload_mtu_review'),

    # Uploading multimedia
    path('<slug:city>/photo/', views.photo_form, name='photo_form'),
    path('<slug:city>/photo/<int:id>/', views.photo_form, name='photo_form'),

    path('<slug:city>/upload/video/', views.upload_video, name='upload_video'),
    path('<slug:city>/upload/video/<int:id>/', views.upload_video, name='upload_video'),

    path('<slug:city>/infrastructure/<slug:type>/<slug:space>/', views.space, name='space'),
    path('<slug:city>/infrastructure/<slug:type>/', views.space_list, name='space_list'),
    path('<slug:city>/infrastructure/<slug:topic>/', views.infrastructure_list, name='infrastructure_list'),
    path('<slug:city>/infrastructure/', views.infrastructure_list, name='infrastructure_list'),

    path('<slug:city>/<slug:main>/<slug:topic>/', views.topic, name='subtopic'),
    path('<slug:city>/<slug:main>/<slug:topic>/input/', views.topic, {'tab': 'input'}, name='subtopic_input'),
    path('<slug:city>/<slug:main>/<slug:topic>/use/', views.topic, {'tab': 'use' }, name='subtopic_use'),
    path('<slug:city>/<slug:main>/<slug:topic>/output/', views.topic, {'tab': 'output'}, name='subtopic_output'),
    #path('<slug:city>/<slug:theme>/<slug:topic>/<slug:type>', views.space_list, name='space_list'),

    # This view is used to show the content of a slide, when recording a video
    path('<slug:city>/slide/', views.temp_slide, name='temp_slide'),

    path('materials/', views.materials, name='materials'),
    path('materials/<slug:catalog>/', views.materials, name='materials'),
    path('<slug:slug>/', views.index, name='city'),
    #path('profile', views.detail, name='profile'),

    # AJAX
    path('search/ajax', views.referencespace_search_ajax, name='referencespace_search_ajax'),

]

src/staf/urls.py
from django.urls import path

from . import views

app_name = 'staf'
urlpatterns = [
    path('', views.index, name='index'),
    path('search', views.search, name='search'),
    path('search/ajax', views.searchajax, name='searchajax'),

    path('processgroups', views.processgroups, name='processgroups'),
    path('processgroups/<int:id>', views.processgroup, name='processgroup'),

    path('materials', views.materiallist, name='materials'),
    path('materials/<int:id>', views.materiallist, name='materiallist'),
    path('materials/<int:id>/edit', views.materialform, name='material_edit'),
    path('materials/<int:id>/child', views.materialchild, name='material_child'),
    path('materials/create', views.materialform, name='material_create'),
    path('materials/ajax', views.materiallistajax, name='materialajax'),
    path('materials/ajax/select2', views.material_search_ajax, name='material_search_ajax'),

    path('processes', views.processlist, name='processes'),
    path('processes/table', views.processtable, name='processtable'),
    path('processes/<int:id>', views.processlist, name='processlist'),
    path('processes/<int:id>/edit', views.processform, name='process_edit'),
    path('processes/<int:id>/child', views.processchild, name='process_child'),
    path('processes/create', views.processform, name='process_create'),
    path('processes/ajax', views.processlistajax, name='processajax'),

    path('processbrowser', views.processlisting, name='processlisting'),
    path('processbrowser/tree', views.processtree, name='processbrowsertree'),
    path('processbrowser/<int:id>', views.processlisting, name='processlisting'),

    path('units', views.units, name='units'),
    path('units/<int:id>', views.unit, name='unit'),

]

src/templates/multiplicity/datasets.all.html
{% extends 'multiplicity/base.html' %}
{% load static %}

{% block title %}Datasets{% endblock %}
{% block container %}stretch-bg-head{% endblock %}

  {% block menu_content %}
    <li class="list-header">{{ page.parent.title }}</li>
    {% for details in list %}
      <li class="list-group-item {% if page.id == details.id %} active-sub{% endif %}"><a href="{% url 'core:sectionpage' details.slug %}">{{ details.title }}</a>
    </li>
    {% endfor %}
  {% endblock %}

  {% block inner_content %}

  {% if datasets %}
    <section id="datasets">
      <div class="row">
        <h3>Datasets</h3>
        {{ page.content|safe }}
      </div>

      <div id="graph">
        <div class="loading text-center text-2x pad-all mar-top">
          <span class="mar-top pad-all">Loading graph</span>
          <i class="fas fa-cog fa-spin mar-top"></i>
        </div>
      </div>

      <div class="alert alert-info">
        We currently have <strong>{{ datasets.count }}</strong> datasets in our database.
      </div>

      <table class="table datatable">
        <thead>
          <tr>
            <th width="300">Dataset</th>
            <th>{{ SYSTEM|title }}</th>
            <th>Preview</th>
          </tr>
        </thead>
        <tbody>
          {% for details in datasets %}
            <tr>
              <td><a href="{% url 'multiplicity:dataset' details.primary_space.slug details.id %}">{{ details.name }}</a></td>
              <td><a href="{{ details.primary_space.get_absolute_url }}">{{ details.primary_space.name }}</a></td>
              <td><a class="btn btn-sm btn-mint" data-space="{{ details.primary_space.slug }}" data-id="{{ details.id }}" data-graph="{{ details.graph.id|default:4 }}" onclick="previewChart({{ details.id }}, {{ details.graph.id|default:4 }}, '{{ details.primary_space.slug }}')"><i class="far fa-fw fa-chart-bar"></i> Preview chart</a></td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </section>

  {% endif %}

  {% endblock %}

{% block head %}
  {% include 'multiplicity/includes/charts.head.html' %}
{% endblock %}

{% block pagehead %}
  <div id="page-head">
      
    <div id="page-title">
        <h1 class="page-header text-overflow">Datasetes</h1>
    </div>

    <ol class="breadcrumb">
      <li><a href="/"><i class="pli-home"></i></a></li>
      <li><a href="{% url 'multiplicity:index' %}">{{ MULTIPLICITY_NAME }}</a></li>
      <li class="active">Datasets</li>
    </ol>

  </div>
{% endblock %}

{% block footer %}
  {% if datasets %}
    {% include 'multiplicity/includes/charts.footer.html' %}
  {% endif %}
{% endblock %}

src/templates/multiplicity/datasets.html
{% extends 'multiplicity/base.html' %}
{% load static %}

{% block title %}Datasets | {{ info.name }} | {{ info.country }}{% endblock %}
{% block container %}stretch-bg-head{% endblock %}

{% block content %}

  {% if datasets %}
    {% include 'multiplicity/includes/datasetlist.html' %}
  {% else %}
    <div class="alert alert-danger">No datasets available yet.</div>
  {% endif %}

{% endblock %}

{% block head %}
  {% include 'multiplicity/includes/charts.head.html' %}
{% endblock %}

{% block sidebar %}
  {% include 'multiplicity/sidebar.default.html' %}
{% endblock %}

{% block pagehead %}
<div id="page-head">
    
    <div id="page-title">
        <h1 class="page-header text-overflow">{{ info.name }}</h1>
    </div>

    <ol class="breadcrumb">
        <li><a href="/"><i class="pli-home"></i></a></li>
        <li><a href="{% url 'multiplicity:index' %}">{{ MULTIPLICITY_NAME }}</a></li>
        <li><a href="{% url 'multiplicity:city' info.slug %}">{{ info.name }}</a></li>
        <li class="active">Datasets</li>
    </ol>

</div>
{% endblock %}

{% block footer %}
  {% if datasets %}
    {% include 'multiplicity/includes/charts.footer.html' %}
  {% endif %}
{% endblock %}

src/templates/multiplicity/sidebar.default.html
<ul id="mainnav-menu" class="list-group">

  {% if page == 'taskforces' %}

    <li class="list-header">Task Forces</li>
    {% for details in taskforces %}
    <li{% if info.id == details.id %} class="active-sub"{% endif %}><a href="{% url 'core:taskforce' details.slug %}">{{ details.name }}</a></li>
    {% endfor %}

  {% endif %}
  {% if section == "data" %}
    <li class="list-header">Data</li>
    <li{% if menu == "index" %} class="active-sub"{% endif %}><a href="{% url 'staf:index' %}">About</a></li>
    <li{% if menu == "materials" %} class="active-sub"{% endif %}><a href="{% url 'staf:materials' %}">Material tree</a></li>
    <li{% if menu == "processes" %} class="active-sub"{% endif %}><a href="{% url 'staf:processes' %}">Process tree</a></li>
  {% elif section == "literature" %}
    <li class="list-header">Literature</li>
    <li{% if page == "publications" %} class="active-sub"{% endif %}><a href="{% url 'core:references' %}">Publications</a></li>
    <li{% if page == "journals" %} class="active-sub"{% endif %}><a href="{% url 'core:journals' %}">Journals</a></li>
    <li{% if page == "events" %} class="active-sub"{% endif %}><a href="{% url 'core:events' %}">Events</a></li>
    <li{% if page == "publishers" %} class="active-sub"{% endif %}><a href="{% url 'core:publishers' %}">Publishers</a></li>
  {% elif section == "more" %}
    <li class="list-header">More</li>
    <li{% if page == "videos" %} class="active-sub"{% endif %}><a href="{% url 'core:videos' %}">Videos</a></li>
    <li{% if page == "blog" %} class="active-sub"{% endif %}><a href="{% url 'core:blog' %}">Blog</a></li>
    <li{% if page == "news" %} class="active-sub"{% endif %}><a href="{% url 'core:news' %}">News</a></li>
  {% elif section == "cities" and info.id %}

  <li class="list-header">{{ info.name }}</li>

  {% if SITE_ID == 1 %}

  <li{% if menu == "dashboard" %} class="active-sub"{% endif %}><a href="{% url 'multiplicity:city' info.slug %}">
  <i class="fal fa-home fa-fw"></i>
      <span class="menu-title">
          Overview
      </span>
  </a>
  </li>

  {% else %}

  <li {% if menu == "profile" %} class="active-sub"{% endif %}>
      <a href="/">
        <i class="fal fa-user-friends fa-fw"></i>
        <span class="menu-title">Overview</span> <i class="arrow"></i>
      </a>

      <ul class="collapse {% if menu == "profile" %}in{% endif %}">
          <li{% if page == "demographics" %} class="active"{% endif %}><a href="{% url 'multiplicity:topic' info.slug 'demographics' %}">Demographics</a></li>
          <li{% if page == "economy" %} class="active"{% endif %}><a href="{% url 'multiplicity:topic' info.slug 'economy' %}">Economy</a></li>
          <li{% if page == "environment" %} class="active"{% endif %}><a href="{% url 'multiplicity:topic' info.slug 'environment' %}">Environment</a></li>
      </ul>
  </li>

  {% endif %}

  <li{% if menu == "infrastructure" %} class="active-sub"{% endif %}>
      <a href="#">
          <i class="fal fa-industry fa-fw"></i>
          <span class="menu-title">Sectors</span>
          <i class="arrow"></i>
      </a>

      <ul class="collapse {% if menu == "sectors" %}in{% endif %}">
        {% for details in info.sectors.all %}
            <li{% if menu == "sectors" and sector == details.process_group %} class="active"{% endif %}><a href="{% url 'multiplicity:sector' info.slug details.process_group.slug %}">{{ details.process_group.name }}</a></li>
        {% endfor %}
      </ul>
  </li>

{% if SITE_ID == 1 %}

  <li style="display:none">
      <a href="/">
        <i class="far fa-fw fa-exchange fa-fw"></i>
        <span class="menu-title">Material flows</span> <i class="arrow"></i>
      </a>

      <ul class="collapse {% if menu == "flows" %}in{% endif %}">
          <li{% if menu == "flows" and page == "biomass" %} class="active"{% endif %}><a href="{% url 'multiplicity:flows' info.slug 'biomass' %}">Biomass</a></li>
          <li{% if page == "fossil-fuels" %} class="active"{% endif %}><a href="{% url 'multiplicity:flows' info.slug 'fossil-fuels' %}">Fossil fuels</a></li>
          <li{% if menu == "flows" and page == "metals" %} class="active"{% endif %}><a href="{% url 'multiplicity:flows' info.slug 'metals' %}">Metals</a></li>
          <li{% if menu == "flows" and page == "minerals" %} class="active"{% endif %}><a href="{% url 'multiplicity:flows' info.slug 'minerals' %}">Minerals</a></li>
          <li{% if page == "water" %} class="active"{% endif %}><a href="{% url 'multiplicity:flows' info.slug 'water' %}">Water</a></li>
          <li{% if page == "waste" %} class="active"{% endif %}><a href="{% url 'multiplicity:flows' info.slug 'waste' %}">Waste</a></li>
          <li{% if page == "emissions" %} class="active"{% endif %}><a href="{% url 'multiplicity:flows' info.slug 'emissions' %}">Emissions</a></li>
      </ul>
  </li>

  {% if False %}
  <li>
      <a href="/">
        <i class="far fa-fw fa-bolt fa-fw"></i>
        <span class="menu-title">Energy flows</span> <i class="arrow"></i>
      </a>

      <ul class="collapse {% if menu == "energy" %}in{% endif %}">
          <li{% if page == "electricity" %} class="active"{% endif %}><a href="{% url 'multiplicity:energy_flows' info.slug 'electricity' %}">Electricity</a></li>
          <li{% if page == "fossil-fuels" %} class="active"{% endif %}><a href="{% url 'multiplicity:energy_flows' info.slug 'fossil-fuels' %}">Fossil fuels</a></li>
          <li{% if page == "renewables" %} class="active"{% endif %}><a href="{% url 'multiplicity:energy_flows' info.slug 'renewables' %}">Renewables</a></li>
          <li{% if page == "nuclear" %} class="active"{% endif %}><a href="{% url 'multiplicity:energy_flows' info.slug 'nuclear' %}">Nuclear energy</a></li>
      </ul>
  </li>
  {% endif %}

  <li style="display:none">
      <a href="/">
        <i class="fal fa-building fa-fw"></i>
        <span class="menu-title">Material stocks</span> <i class="arrow"></i>
      </a>

      <ul class="collapse {% if menu == "stocks" %}in{% endif %}">
          <li{% if menu == "stocks" and page == "biomass" %} class="active"{% endif %}><a href="{% url 'multiplicity:stocks' info.slug 'biomass' %}">Biomass</a></li>
          <li{% if menu == "stocks" and page == "metals" %} class="active"{% endif %}><a href="{% url 'multiplicity:stocks' info.slug 'metals' %}">Metals</a></li>
          <li{% if menu == "stocks" and page == "minerals" %} class="active"{% endif %}><a href="{% url 'multiplicity:stocks' info.slug 'minerals' %}">Minerals</a></li>
      </ul>
  </li>

  <li {% if menu == "profile" %} class="active-sub"{% endif %}>
      <a href="/">
        <i class="fal fa-user-friends fa-fw"></i>
        <span class="menu-title">City profile</span> <i class="arrow"></i>
      </a>

      <ul class="collapse {% if menu == "profile" %}in{% endif %}">
          <li{% if page == "demographics" %} class="active"{% endif %}><a href="{% url 'multiplicity:topic' info.slug 'demographics' %}">Demographics</a></li>
          <li{% if page == "economy" %} class="active"{% endif %}><a href="{% url 'multiplicity:topic' info.slug 'economy' %}">Economy</a></li>
          <li{% if page == "environment" %} class="active"{% endif %}><a href="{% url 'multiplicity:topic' info.slug 'environment' %}">Environment</a></li>
          <li{% if page == "climate" %} class="active"{% endif %}><a href="{% url 'multiplicity:topic' info.slug 'climate' %}">Climate</a></li>
      </ul>
  </li>

  <li{% if menu == "resources" %} class="active-sub"{% endif %}>
      <a href="#">
        <i class="fal fa-file fa-fw"></i>
        <span class="menu-title">Resources</span>
        <i class="arrow"></i>
      </a>

      <ul class="collapse {% if menu == "resources" %}in{%endif %}">
          <li {% if page == "datasets" %} class="active" {% endif %}><a href="{% url 'multiplicity:datasets' info.slug %}">Datasets</a></li>
          <li {% if page == "maps" %} class="active-link"{% endif %}><a href="{% url 'multiplicity:map' info.slug %}">Maps</a></li>
          <li {% if menu == "resources" and type.id == 16 %} class="active" {% endif %}><a href="{% url 'multiplicity:resources' info.slug 'journal-articles' %}">Journal articles</a></li>
          <li {% if menu == "resources" and type.id == 27 %} class="active" {% endif %}><a href="{% url 'multiplicity:resources' info.slug 'reports' %}">Reports</a></li>
          <li {% if menu == "resources" and type.id == 29 %} class="active" {% endif %}><a href="{% url 'multiplicity:resources' info.slug 'theses' %}">Theses</a></li>
          <li {% if page == "photos" %} class="active" {% endif %}><a href="{% url 'multiplicity:photos' info.slug %}">Photos</a></li>
          <li {% if menu == "resources" and page == "links" %} class="active" {% endif %}><a href="{% url 'multiplicity:links' info.slug %}">Links</a></li>
      </ul>
  </li>

{% else %}

  <li{% if menu == "resources" %} class="active-sub"{% endif %}>
      <a href="#">
        <i class="fal fa-file fa-fw"></i>
        <span class="menu-title">Resources</span>
        <i class="arrow"></i>
      </a>

      <ul class="collapse {% if menu == "resources" %}in{%endif %}">
          <li {% if page == "datasets" %} class="active" {% endif %}><a href="{% url 'multiplicity:datasets' info.slug %}">Datasets</a></li>
          <li {% if page == "maps" %} class="active-link"{% endif %}><a href="{% url 'multiplicity:map' info.slug %}">Maps</a></li>
          <li {% if menu == "resources" and type.id == 16 %} class="active" {% endif %}><a href="{% url 'multiplicity:resources' info.slug 'journal-articles' %}">Academic publications</a></li>
          <li {% if menu == "resources" and type.id == 27 %} class="active" {% endif %}><a href="{% url 'multiplicity:resources' info.slug 'reports' %}">Reports</a></li>
          <li {% if page == "videos" %} class="active" {% endif %}><a href="{% url 'multiplicity:photos' info.slug %}">Videos</a></li>
          <li {% if page == "photos" %} class="active" {% endif %}><a href="{% url 'multiplicity:photos' info.slug %}">Photos</a></li>
          <li {% if menu == "resources" and type.id == 24 %} class="active" {% endif %}><a href="{% url 'multiplicity:resources' info.slug 'podcasts' %}">Podcasts</a></li>
          <li {% if menu == "resources" and type.id == 25 %} class="active" {% endif %}><a href="{% url 'multiplicity:resources' info.slug 'presentations' %}">Presentations</a></li>
      </ul>
  </li>

{% endif %}

  <li{% if menu == "upload" %} class="active-sub"{% endif %}><a href="{% url 'multiplicity:upload' info.slug %}">
  <i class="fal fa-upload fa-fw"></i>
      <span class="menu-title">
          Upload
      </span>
  </a>
  </li>

  {% if False %}
    <li{% if menu == "download" %} class="active-sub"{% endif %}><a href="{% url 'multiplicity:download' info.slug %}">
    <i class="fal fa-download fa-fw"></i>
        <span class="menu-title">
            Download
        </span>
    </a>
    </li>
  {% endif %}
{% endif %}

</ul>