src/ie/urls.py
from django.urls import include, path
from django.contrib import admin

" These two are to make file uploads work "
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('data/', include('staf.urls')),
    path('intranet/', include('team.urls')),
    path('', include('core.urls')),
    path('cities/', include('multiplicity.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/team/urls.py
from django.urls import path
from django.contrib.auth import urls
from django.conf.urls import include

from . import views

app_name = 'team'

urlpatterns = [
    path('', views.index, name='homepage'),
    path('controlpanel', views.controlpanel, name='controlpanel'),
    path('category/<int:id>', views.category),
    path('taskforce/<int:id>', views.taskforce, name='taskforce'),
    path('taskforce/<int:category>/task', views.ticket, name='newticket'),
    path('taskforce/<int:id>/leave', views.leavetaskforce, name='leavetaskforce'),
    path('tickets', views.ticketlist, name='tickets'),
    path('tickets/<int:id>', views.ticketdetails, name='ticket'),
    path('tickets/<int:id>/status/<slug:status>', views.ticketstatus, name='ticketstatus'),
    path('tickets/<int:id>/startdiscussion', views.ticketdiscussion, name='ticketdiscussion'),
    path('tickets/<int:id>/progress', views.ticketprogress, name='ticketprogress'),
    path('tickets/<int:id>/assign_to/<int:person>', views.ticketperson, name='ticketperson'),
    path('tickets/<int:id>/edit', views.ticket, name='editticket'),
    path('category/<int:id>/view', views.opencategory, name='viewcategory'),
    path('category/<int:id>/config', views.categoryconfig, name='categoryconfig'),
    path('category/<int:id>/config/save', views.saveconfig, name='saveconfig'),
    path('category/<int:id>/<int:topic>', views.category),
    path('topic/<int:id>', views.topic),
    path('topic/<int:id>/view', views.opentopic, name='topic'),
    path('topic/<int:id>/subscription/<slug:type>', views.subscribetopic, name='topic_subscribe'),
    path('topic/<int:id>/edit', views.edittopic, name='edittopic'),
    path('topic/create', views.createtopic, name='createtopic'),
    path('topic/<int:id>/message', views.createmessage),
    path('message/<int:id>/delete', views.deletemessage, name='deletemessage'),
    path('register', views.register),
    path('taskforces', views.taskforces, name='taskforces'),
    path('search', views.search, name='search'),
    path('profile', views.profile, name='memberprofile'),
    path('profile/save', views.saveprofile, name='saveprofile'),
    path('reports/tickets', views.ticketreport, name='ticketreport'),
    path('projects', views.projects, name='projects'),
    path('projects/<int:id>', views.project, name='project'),
    path('projects/create', views.project, name='createproject'),
]

src/team/models.py
from django.db import models

# So that we can set the user as a foreign key
from django.conf import settings

# So that we can set date = today
from datetime import datetime
from django.contrib.auth.models import User

from django.contrib.auth import get_user_model
User = get_user_model()

from core.models import Color

# To get the total of topics in a category
from django.db.models import Count
from django.forms import ModelForm
from tinymce import HTMLField

class Category(models.Model):
    name = models.CharField(max_length=255)
    google_drive = models.CharField(max_length=255, null=True, blank=True)
    icon = models.CharField(max_length=255, null=True, blank=True)
    category_description = models.TextField(null=True, blank=True);
    entry_exam = models.TextField(null=True, blank=True);
    color = models.ForeignKey(Color, on_delete=models.SET_NULL, null=True, blank=True)
    slug = models.SlugField()
    GROUPS = (
        ('community', 'Community'),
        ('services', 'Services'),
        ('project', 'Project'),
        ('board', 'Administrative board'),
    )
    group = models.CharField(max_length=10, choices=GROUPS, default='community')
    members = models.ManyToManyField(User, through='TaskForceMember')
    position = models.PositiveSmallIntegerField(null=True, blank=True)
    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]

class ProjectTaskforceForm(ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'google_drive']
        labels = { 'name': 'Internal (short) name' }

class ActiveManager(models.Manager):
    def get_queryset(self):
        return super(ActiveManager, self).get_queryset().filter(active=True)

class Topic(models.Model):
    name = models.CharField(max_length=255)
    categories = models.ManyToManyField(Category, related_name='topics')
    subscriptions = models.ManyToManyField(User, related_name='subscribed_to', through='TopicSubscription')
    last_message = models.ForeignKey('Message', on_delete=models.CASCADE, null=True, related_name='last_message')
    created_at = models.DateTimeField(auto_now_add=True)
    deleted_at = models.DateTimeField(null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)
    objects = models.Manager() # The default manager.
    active_objects = ActiveManager() # Only show active topics
    def __str__(self):
        return self.name

    def last_read(self, request):
        read = MessageRead.objects.filter(topic_id=self.id, user_id=request.user.id)

        if read:
            return read[0]
        else:
            return read

class TopicForm(ModelForm):
    class Meta:
        model = Topic
        fields = ['name', 'categories', 'active']

class TopicSubscription(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    NOTIFICATIONS = (
        ('instantly', 'Instant notification'),
        ('daily', 'Daily digest'),
        ('weekly', 'Weekly digest'),
    )
    type = models.CharField(max_length=10, choices=NOTIFICATIONS, default='instantly')

class Message(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    message = models.TextField()
    file = models.FileField(upload_to='uploads/', null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["date"]

class MessageRead(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.PROTECT)
    message = models.ForeignKey(Message, on_delete=models.PROTECT)
    user = models.ForeignKey(User, on_delete=models.PROTECT)

class TaskForceQuerySet(models.QuerySet):
    def leader(self):
        return self.filter(role='leader', end__isnull=True)
    def member(self):
        return self.filter(role='member', end__isnull=True)
    def active(self):
        return self.filter(end__isnull=True).exclude(role='reader')

class TaskForceMember(models.Model):
    taskforce = models.ForeignKey(Category, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    NOTIFICATIONS = (
        ('instantly', 'Instant notification'),
        ('daily', 'Daily digest'),
        ('weekly', 'Weekly digest'),
        ('none', 'No subscription'),
    )
    default_subscription = models.CharField(max_length=10, choices=NOTIFICATIONS, default='instantly')
    ROLES = (
        ('leader', 'Leader'),
        ('member', 'Member'),
        ('reader', 'Reader'),
    )
    role = models.CharField(max_length=10, choices=ROLES, default='member')
    start = models.DateTimeField(auto_now_add=True)
    end = models.DateField(null=True, blank=True)
    notify_of_new_topics = models.BooleanField()
    objects = TaskForceQuerySet.as_manager()
    def __str__(self):
        return '%s (%s)' % (self.user.first_name, self.taskforce.name)

class TaskForceMemberForm(ModelForm):
    class Meta:
        model = TaskForceMember
        fields = ['taskforce', 'default_subscription', 'role', 'notify_of_new_topics']


class Service(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(db_index=True, max_length=255, unique=True)
    description = HTMLField('Description')
    price_range = models.CharField(max_length=255, null=True, blank=True)
    available_members = models.ManyToManyField(User, blank=True)
    possible_partners = HTMLField('Possible partners', blank=True, null=True)
    public = models.BooleanField(default=True)

    def __str__(self):
        return self.title

class Project(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True)
    funders = models.CharField(max_length=255, null=True, blank=True)
    partners = models.CharField(max_length=255, null=True, blank=True)
    our_budget = models.CharField(max_length=255, null=True, blank=True)
    total_budget = models.CharField(max_length=255, null=True, blank=True)
    description = HTMLField('description', null=True, blank=True)
    budget_breakdown = HTMLField('Budget breakdown', null=True, blank=True)
    logos = models.ImageField(null=True, blank=True, upload_to='projectlogos')
    image = models.ImageField(null=True, blank=True, upload_to='projects')
    taskforce = models.ForeignKey(Category, on_delete=models.CASCADE)
    type = models.ForeignKey(Service, on_delete=models.CASCADE,blank=True, null=True)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    public = models.BooleanField(default=True)
    STATUS = (
        ('deciding', 'Not yet internally approved'),
        ('no_go', 'Internal decision not to proceed'),
        ('drafing', 'Internally approved; proposal is being drafted'),
        ('submitted', 'Submitted; in review'),
        ('declined', 'Declined'),
        ('approved', 'Approved; not yet started'),
        ('work', 'Approved; in progress'),
        ('completed', 'Approved; project completed'),
    )
    status = models.CharField(max_length=20, choices=STATUS, default='not_submitted')

    def __str__(self):
        return self.name

class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['name', 'funders', 'partners', 'our_budget', 'total_budget', 'description', 'budget_breakdown', 'type', 'start_date', 'end_date', 'public', 'status']
        labels = { 'name': 'Official project name' }

class TaskForceUnit(models.Model):
    taskforce = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    
    def __str__(self):
        return self.name

class TicketQuerySet(models.QuerySet):
    def completed(self):
        return self.filter(status='completed')
    def pending(self):
        return self.exclude(status='completed').exclude(status='removed')

class TaskForceTicket(models.Model):
    taskforce = models.ForeignKey(Category, on_delete=models.CASCADE)
    assigned_to = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, limit_choices_to={'is_staff': True})
    title = models.CharField(max_length=255)
    description = HTMLField('description', null=True, blank=True)
    STATUS = (
        ('unassigned', 'Unassigned'),
        ('assigned', 'Assigned'),
        ('in_progress', 'In Progress'),
        ('shelved', 'Shelved'),
        ('completed', 'Completed'),
        ('removed', 'Removed'),
    )
    LEVELS = (
        ('low', 'Low'),
        ('medium', 'Medium'),
        ('high', 'High'),
    )
    urgency = models.CharField(max_length=6, choices=LEVELS, default='medium')
    importance = models.CharField(max_length=6, choices=LEVELS, default='medium')
    complexity = models.CharField(max_length=6, choices=LEVELS, default='medium')
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20, choices=STATUS, default='unassigned')
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, null=True, blank=True)
    unit = models.ForeignKey(TaskForceUnit, on_delete=models.CASCADE, null=True, blank=True)
    deadline = models.DateField(null=True, blank=True)
    good_entry_task = models.BooleanField(default=False)
    objects = TicketQuerySet.as_manager()

class TaskForceTicketForm(ModelForm):
    class Meta:
        model = TaskForceTicket
        fields = ['title', 'description', 'assigned_to', 'status', 'importance', 'urgency', 'complexity', 'unit', 'deadline', 'good_entry_task']

class TicketLog(models.Model):
    ticket = models.ForeignKey(TaskForceTicket, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = HTMLField('description', null=True, blank=True)

# Always show the first name instead of username

src/templates/team/category.config.html
{% extends 'multiplicity/base.html' %}
{% load bootstrap3 %}
{% load static %}

{% block title %}
Edit task force
{% endblock %}

{% block head %}
<style type="text/css">
textarea.form-control{height:100px}
p.jumpdown{margin-top:50px;text-align:right}
.form-group:first-child{display:none;font-weight:bold}
</style>
{% endblock %}

{% block content %}

<h2>Configuration: {{ category.name }}</h2>

<form action="{% url 'team:categoryconfig' category.id %}" method="post" class="form form-horizontal">
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Save' layout='horizontal' %}{% endbuttons %}
    {% csrf_token %}
</form>

<p class="jumpdown"><a href="{% url 'team:homepage' %}">Back</a></p>

{% endblock %}


{% block footer %}
<script type="text/javascript">
$(function(){
  $("#id_default_subscription").change(function(){
    subscription = $(this).val();
    checkbox = $(".checkbox");
    if (subscription == "instantly") {
      $(checkbox).closest(".form-group").hide('fast');
    } else {
      $(checkbox).closest(".form-group").show('fast');
    }
  });
  $("#id_default_subscription").change();
});
</script>
{% endblock %}

src/templates/team/chat.html
{% load static %}
<div class="panel">

    <p class="alert alert-success nobottommargin">
      <span class="subscribers">
      Subscriber(s):
      {% for member in members %}
        <span class="badge badge-{% if member.type == "instantly" %}info{% elif member.type == "weekly" %}primary{% elif member.type == "daily" %}warning{% endif %}">
        {{ member.user.first_name }}
        </span>
      {% endfor %}
      </span>
        <span class="subscription">
        Manage your subscription:
        {% if subscribed %}
          <a class="pull-right badge badge-danger" href="{% url 'team:topic_subscribe' topic.id 'unsubscribe' %}">Unsubscribe</a>
        {% endif %}
          <a class="pull-right badge badge-primary" href="{% url 'team:topic_subscribe' topic.id 'weekly' %}">Weekly digest</a>
          <a class="pull-right badge badge-warning" href="{% url 'team:topic_subscribe' topic.id 'daily' %}">Daily digest</a>
          <a class="pull-right badge badge-info" href="{% url 'team:topic_subscribe' topic.id 'instantly' %}">Instantly</a>
        </span>
        <a class="pull-right badge badge-default" id="subscription" href="#">{% if subscribed %}Manage subscription{% else %}Subscribe{% endif %}</a>
    </p>

    <div class="media-block pad-all bord-btm">
        <div class="media-left">
            {% with 'moc/team/team.'|add:topic.author.first_name|lower|add:'.jpg' as image_static %}
              <img class="img-circle img-xs" src="{% static image_static %}" alt="">
            {% endwith %}
        </div>
        <div class="media-body">
            <p class="mar-no text-main text-bold text-lg">{{ topic.name }}
            <a href="{% url 'team:edittopic' topic.id %}"><i class="fa fa-pencil-alt"></i></a>
            </p>
            <small class="text-muteds">Thread opened by {{ topic.author.first_name }} on {{ topic.created_at }}</small>
            Posted in: 
            {% for category in categories %}
                <a href="{% url 'team:viewcategory' category.id %}">
                    <span class="badge badge-warning">{{ category.name }}</span>
                </a>
            {% endfor %}
            {% if ticket %}
              <a class="badge badge-success" href="{% url 'team:ticket' ticket.id %}">View task</a>
            {% endif %}
        </div>
    </div>

    <div class="nano" style="height: 56vh">
        <div class="nano-content">
            <div class="panel-body chat-body media-block">
                {% for info in list.all %}
                <div class="chat-{% if info.author == user %}me{% else %}user{% endif %}">
                    <div class="media-left">
                        {% with 'moc/team/team.'|add:info.author.first_name|lower|add:'.jpg' as image_static %}
                          <img src="{% static image_static %}" class="img-circle img-sm" alt="">
                        {% endwith %}
                    </div>
                    <div class="media-body">

                        <div>
                            <p>{{ info.message|linebreaksbr|urlizetrunc:30 }}
                            <small>{{ info.author.first_name }} | {{ info.date|timesince }} ago
                            {% if info.author == request.user %}
                            | <a class="delete" href="{% url 'team:deletemessage' info.id %}" onclick="javascript:return confirm('Are you sure?')">delete this post</a>
                            {% endif %}
                            </small>
                            </p>
                        </div>

                    </div>
                </div>
                {% endfor %}
                <!--
                <div class="chat-meta-day"><span class="badge">Previous messages</span></div>
                <div class="chat-meta-day"><span class="badge">Load older messages</span></div>
                -->
            </div>
        </div>
    <div class="nano-pane"><div class="nano-slider" style="height: 80px; transform: translate(0px, 37.9179px);"></div></div></div>
    <form action="/intranet/topic/{{ topic.id }}/message" method="post">
        {% csrf_token %}
        <div class="pad-all">
            <div class="input-group">
                 <textarea placeholder="Type your message" class="form-control" type="text" name="message" required></textarea>
                 <span class="input-group-btn">
                     <button class="hide btn btn-icon add-tooltip" data-original-title="Add file" type="button"><i class="pli-paperclip icon-lg"></i></button>
                     <button class="btn btn-icon add-tooltip" data-original-title="Send" type="submit"><i class="pli-yes icon-lg"></i></button>
                 </span>
             </div>
            Use CTRL+Enter to submit message
        </div>
    </form>
    <div class="pad-all" id="savingmessage">
      <i class="fa fa-spinner fa-lg"></i> Saving your message... stay tuned...
    </div>
</div>

<script src="{% static 'ie/js/nifty.min.js' %}"></script>
<script type="text/javascript">
$(function(){
  $("#chat .nano-content").scrollTop($("#chat .nano-content")[0].scrollHeight);
  $("#chat .nano-content a:not(.delete)").attr("target", "_blank");
  $("#subscription").click(function(e){
    e.preventDefault();
    $(this).hide()
    $(".subscribers").hide();
    $(".subscription").show();
  });
});
</script>

src/templates/team/projects.html
{% extends 'multiplicity/base.html' %}
{% load static %}

{% block title %}
Projects
{% endblock %}

{% block container %}

{% endblock %}

{% block head %}
{% endblock %}

{% block content %}

    <ol class="breadcrumb">
        <li><a href="/"><i class="pli-home"></i></a></li>
        <li><a href="{% url 'team:controlpanel' %}">Back-end</a></li>
        <li class="active">Projects</li>
    </ol>

    <h3>Projects</h3>

    <table class="table table-striped">
      <thead>
      <tr>
        <th>Name</th>
        <th>Funder</th>
        <th>Our budget</th>
        <th>Start</th>
        <th>End</th>
        <th>Status</th>
      </tr>
      </thead>
      <tbody>
      {% for project in projects %}
        <tr>
          <td><a href="{% url 'team:taskforce' project.taskforce.id %}">{{ project.taskforce.name }}</a></td>
          <td>{{ project.funders|default_if_none:"" }}</td>
          <td>{{ project.our_budget|default_if_none:"" }}</td>
          <td>{{ project.start_date|default_if_none:"" }}</td>
          <td>{{ project.end_date|default_if_none:"" }}</td>
          <td>{{ project.get_status_display }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    <p><a href="{% url 'team:createproject' %}" class="btn btn-success"><i class="fas fa-plus fa-fw"></i> Add project</a></p>

{% endblock %}

{% block sidebar %}

{% endblock %}

src/templates/team/ticket.html
{% extends 'multiplicity/base.html' %}
{% load bootstrap3 %}
{% load static %}

{% block title %}
Discussion board
{% endblock %}

{% block container %}

{% endblock %}

{% block head %}
{% endblock %}

{% block content %}

    <ol class="breadcrumb">
        <li><a href="/"><i class="pli-home"></i></a></li>
        <li><a href="{% url 'team:controlpanel' %}">Back-end</a></li>
        {% if category.group == 'project' %}
          <li><a href="{% url 'team:projects' %}">Projects</a></li>
        {% endif %}
        <li><a href="{% url 'team:taskforce' info.taskforce.id %}">{{ info.taskforce.name }}</a></li>
        {% if edit %}
          <li><a href="{% url 'team:ticket' info.id %}">{{ info.title }}</a></li>
          <li class="active">Edit ticket</li>
        {% else %}
          <li class="active">New ticket</li>
        {% endif %}
    </ol>

  <h2>Task</h2>

  {% if edit %}
    <form action="{% url 'team:editticket' info.id %}" method="post" class="form form-horizontal">
  {% else %}
    <form action="{% url 'team:newticket' category.id %}" method="post" class="form form-horizontal">
  {% endif %}
      {% csrf_token %}
      {% bootstrap_form form layout='horizontal' %}
      {% buttons %}
          <div class="col-sm-offset-3 col-sm-9">
            <button type="submit" class="btn btn-success">
              Save
            </button>
          </div>
         </div>
      {% endbuttons %}
  </form>

  <p class="jumpdown"><a href="{% url 'team:taskforce' category.id %}">Back to task force</a></p>

{% endblock %}

{% block sidebar %}

{% endblock %}

{% block footer %}
<script type="text/javascript">
$(function(){
  $("#id_deadline").attr("type", "date");
  {% if info.taskforce.id != 10 %}
    $("#id_unit").closest(".form-group").hide();
  {% endif %}
});
</script>
{% endblock %}

src/templates/team/ticket.list.html
{% extends 'multiplicity/base.html' %}
{% load static %}

{% block title %}
Discussion board
{% endblock %}

{% block container %}

{% endblock %}

{% block head %}
{% endblock %}

{% block content %}

    <ol class="breadcrumb">
        <li><a href="/"><i class="pli-home"></i></a></li>
        <li><a href="{% url 'team:controlpanel' %}">Back-end</a></li>
        <li class="active">Task report</li>
    </ol>

    <h3>Task report</h3>

    <p>
      Show: 
      <a class="btn btn-{% if show == 'all' %}info{% else %}default{% endif %}" href="{% url 'team:tickets' %}?show=all&amp;status={{ set_status }}&amp;user={{ user }}">All task forces</a>
      <a class="btn btn-{% if show == 'my_taskforces' %}info{% else %}default{% endif %}" href="{% url 'team:tickets' %}?show=my_taskforces&amp;status={{ set_status }}&amp;user={{ user }}">My task forces</a>
    </p>

    <p>
      User: 
      <a class="btn btn-{% if user == 'all' %}info{% else %}default{% endif %}" href="{% url 'team:tickets' %}?show={{ show }}&amp;status={{ set_status }}&amp;user=all">All</a>
      {% for userinfo in users %}
        <a class="btn btn-{% if userinfo.id == user %}info{% else %}default{% endif %}" href="{% url 'team:tickets' %}?show={{ show }}&amp;status={{ set_status }}&amp;user={{ userinfo.id }}">{{ userinfo }}</a>
      {% endfor %}
    </p>

    <ul class="nav nav-tabs nav-tabs-inverted">
      <li class="{% if set_status == "all" %}active{% else %}regular{% endif %}"><a href="{% url 'team:tickets' %}?show={{ show }}&amp;status=all&amp;user={{ user }}">All tasks</a></li>
      {% for key, status in status_list %}
        <li class="{% if set_status == key %}active{% else %}regular{% endif %}"><a href="{% url 'team:tickets' %}?show={{ show }}&amp;status={{ key }}&amp;user={{ user }}">{{ status }}</a></li>
      {% endfor %}
    </ul>
    <div class="boxit pad-all">
    <table class="table table-striped datatable">
    <thead>
      <tr>
        <th>Task</th>
        <th>Task force</th>
        <th>Status</th>
        <th>Assigned to</th>
      </tr>
      </thead>
      <tbody>
      {% for info in list %}
        <tr>
          <td><a href="{% url 'team:ticket' info.id %}">{{ info.title }}</a>
          <td><a href="{% url 'team:taskforce' info.taskforce.id %}">{{ info.taskforce.name }}</a></td>
          <td>{{ info.get_status_display }}</td>
          <td>{{ info.assigned_to }}</td>
        </tr>
      {% endfor %}
      </tbody>
      </table>
      </div>

{% endblock %}

{% block sidebar %}

{% endblock %}

src/templates/team/ticket.report.html
{% extends 'multiplicity/base.html' %}
{% load static %}

{% block title %}
Discussion board
{% endblock %}

{% block container %}

{% endblock %}

{% block head %}
{% endblock %}

{% block content %}

    <ol class="breadcrumb">
        <li><a href="/"><i class="pli-home"></i></a></li>
        <li><a href="{% url 'team:controlpanel' %}">Back-end</a></li>
        <li class="active">Progress report</li>
    </ol>

    <h3>Progress report</h3>

    <p>
      Show: 
      <a class="btn btn-{% if show == 'all' %}info{% else %}default{% endif %}" href="{% url 'team:ticketreport' %}?show=all&amp;tasks={{ filter_task }}&amp;user={{ user }}">All task forces</a>
      <a class="btn btn-{% if show == 'my_taskforces' %}info{% else %}default{% endif %}" href="{% url 'team:ticketreport' %}?show=my_taskforces&amp;tasks={{ filter_task }}&amp;user={{ user }}">My task forces</a>
    </p>

    <p>
      User: 
      <a class="btn btn-{% if user == 'all' %}info{% else %}default{% endif %}" href="{% url 'team:ticketreport' %}?show={{ show }}&amp;tasks={{ filter_task }}&amp;user=all">All</a>
      {% for userinfo in users %}
        <a class="btn btn-{% if userinfo.id == user %}info{% else %}default{% endif %}" href="{% url 'team:ticketreport' %}?show={{ show }}&amp;tasks={{ filter_task }}&amp;user={{ userinfo.id }}">{{ userinfo }}</a>
      {% endfor %}
    </p>

    <ul class="nav nav-tabs nav-tabs-inverted">
      <li class="{% if filter_task == "all" %}active{% else %}regular{% endif %}"><a href="{% url 'team:ticketreport' %}?show={{ show }}&amp;tasks=all&amp;user={{ user }}">All actions</a></li>
      <li class="{% if filter_task == "new" %}active{% else %}regular{% endif %}"><a href="{% url 'team:ticketreport' %}?show={{ show }}&amp;tasks=new&amp;user={{ user }}">Tasks created</a></li>
      <li class="{% if filter_task == "updates" %}active{% else %}regular{% endif %}"><a href="{% url 'team:ticketreport' %}?show={{ show }}&amp;tasks=updates&amp;user={{ user }}">Progress update</a></li>
      <li class="{% if filter_task == "completed" %}active{% else %}regular{% endif %}"><a href="{% url 'team:ticketreport' %}?show={{ show }}&amp;tasks=completed&amp;user={{ user }}">Tasks completed</a></li>
    </ul>
    <div class="boxit pad-all">
    <table class="table table-striped datatable">
    <thead>
      <tr>
        <th width="100">Date</th>
        <th>Person</th>
        <th>Task</th>
        <th>Task force</th>
        <th width="200">Action</th>
      </tr>
      </thead>
      <tbody>
      {% for info in log %}
        <tr>
          <td data-sort="{{ info.created_at|date:"YmdHis" }}">{{ info.created_at|date:"M d, Y" }}</td>
          <td>{{ info.user }}</td>
          <td><a href="{% url 'team:ticket' info.ticket.id %}">{{ info.ticket.title }}</a>
          <td><a href="{% url 'team:taskforce' info.ticket.taskforce.id %}">{{ info.ticket.taskforce.name }}</a></td>
          <td>{{ info.title }}
          {% if info.description %}<br>
          <em>{{ info.description|linebreaksbr }}</em>
          {% endif %}
          </td>
        </tr>
      {% endfor %}
      </tbody>
      </table>

{% endblock %}

{% block sidebar %}

{% endblock %}ac